### ISSUE TITLE
idea: use stackexchange for support and to build community

### ISSUE THREAD

**Issue by marks** [socrata/opendatanetwork.com#143]
I feel like the site needs a way for people to a) ask questions as well as b) provide feedback.

For a few reasons, I think (a) can be covered by StackExchange much like `openfda` has leveraged it. We can also start to try to build a community of people to answer each other's questions and drive organic traffic to the ODN site. I, personally, am willing to monitor the `opendatanetwork` tag on SE if we decide to do this.

For (b), I think a Github Issues or email would be better.

**Comment by timothyclemansinsea** [comment]
What's the status of this idea now that ODN is open source and Github issues is now used on dev.socrata.com?
