### ISSUE TITLE
Re-enable oncall notifications once our house is in order

### ISSUE THREAD

**Issue by chrismetcalf** [socrata/opendatanetwork.com#199]

**Comment by aaasen** [comment]
Since everything else in `v.reliability` is closed, can we re-enable oncall now?

**Comment by chrismetcalf** [comment]
I thought I had access to PagerDuty but it doesn't look like I do anymore. @zang0, do you have access?

**Comment by zang0** [comment]
Doesn't look like it. Can you get from IT?

**Comment by zang0** [comment]
how's this going?
