### ISSUE TITLE
bring in 1st education pt map under education tab

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#227]
use @chrismetcalf headstart? pt locations as a start.

**Comment by aaasen** [comment]
First pass review app: https://opendatanetwork-staging-pr-322.herokuapp.com/region/1600000US5363000/Seattle_WA/education_places/head_start_center?

Includes pulling in only points in the view of the map, changing classification, marker clustering, and detailed base maps. @zang0 feedback appreciated. Don't have much time but I would like to get this on staging in some form before I go on break.

Park and landmark options will go away - just included them to a get a feel for the data.

**Comment by zang0** [comment]
In a mtng, but Some quick comments:

_1 Can we add more info on the head start center places, do they have a name? If not, lets just add Head Start Center above the current info

_2 Landmarks and Parks don't feel relevant to the Education classification. That data set did, however, have a bunch that were relevant, stuff like: Elementary Schools, Libraries, Alternative Schools, Environmental Learning Centers, etc.

_3 Can we add a summary sentence that says: "Seattle, WA has 223 Head Start Centers"

**Comment by aaasen** [comment]
1. Added description to tooltip which is something like "Head Start" or "Early Head Start". For other types of points, the descriptions were links so I transformed them into real links. See [playfields](http://localhost:3000/region/1600000US5363000/Seattle_WA/education_places/playfields?) for a good example. Unfortunately a lot of the links are 404s. 
2. Added categories from meeting.
3. Covered by #323 
4. Thanks!
5. Also covered by #323.

**Comment by zang0** [comment]
Looking good! Can we add the type underneath the name, e.g.

Sacajewea
Elementary School
blah

**Comment by aaasen** [comment]
Added it. Only problem is that it can seem redundant for head start centers. For example: 
<img width="249" alt="screen shot 2016-03-10 at 4 21 54 pm" src="https://cloud.githubusercontent.com/assets/1320603/13689217/41096e88-e6dc-11e5-8c2a-748217e025ca.png">
