### ISSUE TITLE
dataset 'Popular Values' brutally slow

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#239]
I'm concerned about the performance of the 'Popular Values' call - See image attached. I'm seeing requests taking over a minute! I'm also concerned about the Google bot hitting these pages and bringing our site down by attempting hundreds of thousands of these page loads in 1 visit. One idea is to nofollow links in and noindex the pages; that doesn't address other bots that might not respect. Another option is to enforce some timeouts. Thoughts?

![screen shot 2016-02-17 at 12 36 02 pm](https://cloud.githubusercontent.com/assets/1051776/13123860/3b1e0148-d573-11e5-84c2-931f51080185.png)
![screen shot 2016-02-17 at 12 35 44 pm](https://cloud.githubusercontent.com/assets/1051776/13123861/3b305014-d573-11e5-95a1-ce1158da3ba2.png)

**Comment by ToshMeston** [comment]
The datasets page can be dealing with either an old backend or new backend dataset.  What we can to do is the following:

If old (newBackend: false):
Get the columns which should include the cacheContents and display them.  
Call the migrations api to get the nbeId if available.  
Use nbeId to display the "view top 100" link.

If new (newBackend: true):
Call the migrations api to get the obeId if available.
Fetch the dataset with the obeId and display the columns.
Use the nbeId to display the "view top 100" link.

**Comment by ToshMeston** [comment]
OK, I think I have all the cases covered - datasets on the obe, datasets on the nbe, either when the migrations request succeeds or fails.  If we have an nbe dataset and the obe exists, I look up the nbe fields on the obe and pull in the obe's cachedContents into the nbe.  An nbe dataset will display its own columns, and they may or may not have sample values.  An obe dataset displays it's own columns and cachedContests if they exist.  The sample values are always from the obe.  Further, if we have an obe dataset, and the migrations request fails to look up with nbeId, there will be no "view top 100" link.

To help understand where the dataset is coming from, you can append ?debug=1 to the URL to write some debug info to the browser console.

http://localhost:3000/dataset/opendata.utah.gov/5w3b-b6r9?debug=1
{"id":"5w3b-b6r9","nbeId":"gfwc-y9mk","obeId":"5w3b-b6r9","newBackend":false}

http://localhost:3000/dataset/opendata.utah.gov/gfwc-y9mk?debug=1
{"id":"gfwc-y9mk","nbeId":"gfwc-y9mk","obeId":"5w3b-b6r9","newBackend":true}

http://localhost:3000/dataset/data.seattle.gov/pvkf-73v3?debug=1
{"id":"pvkf-73v3","nbeId":null,"obeId":"pvkf-73v3","newBackend":false,"migrationsError":true}

@zang, can you help to test this and let me know if you see anything that should be changed?  Thx.

**Comment by ToshMeston** [comment]
This is checked into staging, but please take a look and make sure that I didn't miss something.  Thanks.

**Comment by zang0** [comment]
looks great! killing this beast.

**Comment by zang0** [comment]
here we go again. 

looks like your logic for view top 100 is broke now. seriously need to add some tests
http://opendatanetwork-staging.herokuapp.com/dataset/brigades.opendatanetwork.com/xprd-yiwz
totally broke
autosuggest off crime, all entries have no top 100

**Comment by zang0** [comment]
looks fixed
