### ISSUE TITLE
change meta description tag

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#240]
change the HTML tag:

`<meta name="description" content="blah" />`

to a slight augmentation of the generated summary sentences. Example, for: 

http://www.opendatanetwork.com/region/1600000US4159000-1600000US5363000/Portland_OR-Seattle_WA/earnings/median_female_earnings/2013

show 

`<meta name="description" content="Maps, charts and data show the median female earnings of Portland, OR in 2013 was $27,101. The median female earnings of Seattle, WA in 2013 was $34,599." /> `

This will be the summary snippet shown by Google in search results.

**Comment by zang0** [comment]
Note: the meta description field is character count constrained by Google, so subsequent geo region sentence are more terse than in the generated summary sentence. Specifically:

` <meta name="description" content="Maps, charts and data show the population count of Seattle, WA in 2013 was 624,681. Maps, charts and data show the population count of Portland, OR in 2013 was 594,687.">`

should be

`<meta name="description" content="Maps, charts and data show the population count of Seattle, WA in 2013 was 624,681. Population count of Portland, OR in 2013 was 594,687.">`

Note that the "Maps, charts and data show the" is NOT repeated after the first sentence.

**Comment by ToshMeston** [comment]
OK, removed the "Maps, charts and data..." on the non-first sentences.  The new meta description reads thus: "Maps, charts and data show the population rate of change of Seattle Metro Area (WA) in 2013 was 1.5%. The population rate of change of Portland Metro Area (OR-WA) in 2013 was 1.3%."

Fixed.
