### ISSUE TITLE
Need automated tests to stop blatant wonks

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#243]
We should start building out some simple tests to ensure that wildly embarassing things don't happen, like us releasing w/ this bug:

https://github.com/socrata/opendatanetwork.com/issues/242

I'm not usually on the look out for this type of problem.

**Comment by chrismetcalf** [comment]
@zang0 How high of a priority is cross-browser testing? That'll make a difference as to whether I can use something simple like [PhantomJS](http://phantomjs.org/) (WebKit) or if I have to go all-in on a Selenium-based solution like [Sauce Labs](https://saucelabs.com/).

**Comment by chrismetcalf** [comment]
As discussed with @zang0, I'll start first with PhantomJS

**Comment by zang0** [comment]
punting

**Comment by zang0** [comment]
Can we push on this early before sparks start flying on the next release?

**Comment by chrismetcalf** [comment]
I’d like to get a step further on the OpenAPI spec work, and I can tackle this next.
On March 7, 2016 at 12:10:32 PM, zang0 (notifications@github.com) wrote:

Can we push on this early before sparks start flying on the next release?

**Comment by zang0** [comment]
How's this coming?

**Comment by chrismetcalf** [comment]
Alright, getting casperjs integrated with gulp was a pain in the butt, but basic homepage tests are in, and Travis is set up.

Details are in README.md, but here's an overview:

- Tests are run by Travis automagically whenever changes are pushed to GitHub or pull requests are created
- Notifications are automatically sent to #odn-automation and our emails when things break
- Run `gulp test` to manually run the tests

The included test runs through a few basic checks on the homepage - searching for a couple of different things, checks for highlighted content, etc. It should be a good model for other pages.

**Comment by zang0** [comment]
Fantastic!
