### ISSUE TITLE
all dataset pages yield 500

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#247]
getting 500s on all dataset landings, see:

http://opendatanetwork-staging.herokuapp.com/dataset/data.cityofchicago.org/ijzp-q8t2
http://opendatanetwork-staging.herokuapp.com/dataset/data.cityofchicago.org/dfnk-7re6
http://opendatanetwork-staging.herokuapp.com/dataset/data.seattle.gov/3k2p-39jp

**Comment by zang0** [comment]
looks like this is back. to tosh who I believe was making changes here.

**Comment by zang0** [comment]
not all, but many now. here's some:

http://opendatanetwork-staging.herokuapp.com/dataset/data.kingcounty.gov/g65a-m5nb
http://opendatanetwork-staging.herokuapp.com/dataset/data.murphytx.org/ks6s-d2hj
http://opendatanetwork-staging.herokuapp.com/dataset/data.seattle.gov/xa6k-4q2h

**Comment by ToshMeston** [comment]
OK, fixed.  These datasets immediately above do not return cachedContents in the response.  Added the null check and also we will not display the "Sample Values" column at all if no field has them.  On staging.
