### ISSUE TITLE
add quick links to right of search bar

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#250]
Want quick links to go straight to the respective pages, i.e. no 'refine by' just to the category, region, etc. page. See attached images. Also:

_1. want a "more" @ the bottom to add another 15 rows worth of stuff.

_2. delete the 'Data by category' on the homepage

![screen shot 2016-02-22 at 2 39 25 pm](https://cloud.githubusercontent.com/assets/1051776/13235339/4183218c-d972-11e5-9b41-d6962c05e06a.png)
![screen shot 2016-02-22 at 2 38 49 pm](https://cloud.githubusercontent.com/assets/1051776/13235340/41912214-d972-11e5-9549-444e7d0f1d84.png)

here is a link to what the quick links dropdown would look like:
https://www.dropbox.com/s/qwn76vzltjpiz63/ODN-results_refine_V13_quicklinks.jpg?dl=0

**Comment by ToshMeston** [comment]
Fixed.
