### ISSUE TITLE
+ two tier menu + 1 column Maps/Charts/Datasets

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#253]
Some shots below of the new design:

here is the link to the over all page layout: 
https://www.dropbox.com/s/sg9e7cwtw004uhx/ODN-results_refine_V13.psd?dl=0

here is a link to what the second level nav drop down would look like:
https://www.dropbox.com/s/5gsmhl6v0gxjwu6/ODN-results_refine_V13_GDP.jpg?dl=0

here is a link to what the quick links dropdown would look like:
https://www.dropbox.com/s/qwn76vzltjpiz63/ODN-results_refine_V13_quicklinks.jpg?dl=0

Note:  the 'Data from the 2013 blah' citation should be inside the gray dataset description box above it. 

background discussion on the design evolution @ #211

**Comment by ToshMeston** [comment]
@zang0 will split the quick links menu from this and assign to me.  I created branch iss253 for @aaasen to hook up the second tier menus.  Thanks.

**Comment by ToshMeston** [comment]
Quicklinks is #250.

**Comment by aaasen** [comment]
This is in staging. Reopen if you find issues.
