### ISSUE TITLE
cap 'Sample Values' line length

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#254]
for text description values, some run really long, see: 

http://opendatanetwork-staging.herokuapp.com/dataset/data.seattle.gov/55z8-f4gi

lets cap at nearest word boundary that fits on 1 line and add '...' at the end.

**Comment by ToshMeston** [comment]
I'll probably die before text-overflow: ellipsis breaking on a word boundary works natively in CSS.  For now, I've added jquery.dotdotdot to do this.  Fixed and pushed, but Heroku is unavailable, and the change did not propagate to staging.  Eventually it will.
