### ISSUE TITLE
remove async in dataset pages

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#256]
current probs manifested:

1. view top 100 links not always clickable

sometimes i can click on the view top 100 links, othertimes they go no where. inspecting the HTML yields these:

<a class="view-top-100" rel="nofollow">view top 100</a>

2. content contributions not helping w/ SEO

can we:

1. eliminate the asynchronous behavior? the new call is very fast, and I think the extra complexity is no longer needed

2. eliminating the asynchronicity should also let us get the content into the HTML to help w/ page SEO

3. that should simplify the link execution w. a normal href

**Comment by ToshMeston** [comment]
All right.  It seems we can get the cachedContent either via the nbeId or obeId so am just using the dataset at hand.  We are rendering the "view top 100" link for all data types, except location, which does not support the the group by query.  Fixed.
