### ISSUE TITLE
Sample Values w/ 1 result don't have view top 100 link

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#257]
http://opendatanetwork-staging.herokuapp.com/dataset/bronx.lehman.cuny.edu/2y6n-fdxk

note: no View Top 100 link

is this because the summary data only contains 1? what happens when we follow the View Top 100 link, would we get more data? If so, lets ensure the link is there.

**Comment by ToshMeston** [comment]
We were not showing the "view top 100" if there were fewer than 5 sample values.  Now it show when there are > 0.  Fixed.
