### ISSUE TITLE
+ generate pipe to data: public safety seeded w/ crime summary stats

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#272]
high level:

intro moto based summary crime stats into a new tab called public safety w/ sub category crime. End result will look something like this: http://www.opendatanetwork.com/region/1600000US5363000/Seattle_WA/earnings/median_earnings/2013

where drop downs in the map are by crime type, and summary timeline stats are total crimes.

reqs:

1. user should be able to see a crime map + charts and toggle by type of crime, i.e. assault. 
2. user should be able to compare cities (rolled up geo regions will happen post take 1) for which we have crime data (suggested comparison autosuggest is constrained to appropriate datasets)
3. summary stats will be broken down by month going back 36 months
4. crime data needs to be per capita normalized (# incidents / 10K population) - take (#crimes/#people)*10000. Per capita normalization should use our most recent measured data (2013)
5. charts should include timeline data where take 1 includes the sum across all crime types. Take 2 we'll tackle an in chart toggle across all individual crime types
6. for queries corresponding to region/sub-topic, we'll use the data set expansion query terms: crime, police, arrest, warrant
 
details:

_1. pipeline

_1.1 access every agency

we need the pipeline to access this data set:

https://moto.data.socrata.com/dataset/Agencies-NBE/fax2-dw8p

which lists all agencies. 

_1.2 access itemized agency data

for every agency, the process then needs to access individual detailed crime states for an agency,

 examples:

https://moto.data.socrata.com/dataset/King-County-Sheriff-s-Office/4h35-4mtu
https://moto.data.socrata.com/dataset/Washington-DC/2vfk-6rp4

_1.3 resolve USCensusIds for each place

we then need to walk through and resolve to our uscensusid's using this data set: https://odn.data.socrata.com/view/p5cc-m8dh

lets try a fuzzy name match + geo radius constraint

_1.4 rollup by month and crime type

we'd then generate a list of summary stats (monthly totals in each of the categories under the incident_type_primary column going back in time 36 months from current including only complete months)

_2. wire in data set

_3. test

**Comment by zang0** [comment]
per meeting, here's the plan:

1. @chrismetcalf to get a static snapshot dataset together by using the city polygon boundaries across incident locations. take 1 will be just using a handful of agency data. I suggest a fallback where you figure out the city name matches given incidents that do have lat longs, and apply those to exact city name matches for incidents that don't

2. @aaasen  to wire into ODN the small snapshot data set monday of next week

3. if chris's approach runs into snags, lane to pursue a client side uscensusid mapping approach and move forward

4. chris to cycle back and hit the rest of the agencies

5. chris to pipeline

**Comment by zang0** [comment]
slack convo - OK here’s the proposed schema that I’ll be loading into: https://odn.data.socrata.com/dataset/Crime-Statistics-Aggregate-by-Year-Month-and-City/b9cw-c7zm


I combined all of the US Census “Places” Tiger LINE data files to get nationwide set of city polygons

From the listing of agency datasets I then pull down all of the agency instance data, and check to see if it has an incident location or not. If it doesn’t have an incident location, I use the center point provided for the agency. Then I intersect that against my city polygons, discard anything that falls outside a city, discard anything without a date, truncate the datetime to just year-month, aggregate it by geo, incident_parent_type, and date time, and plop it in that dataset

That’s a sample set of data based off just the first 100 rows for the first 50 agencies. 

fantastic! are you thinking a follow up FME job to transform this dataset into comparable forms of our other datasets? I’m presuming we want to get to something w/ column names like:

id, name, type, year, month, crime_type_1_count, crime_type_1_normalized_incident_rate, crime_type_2_count, crime_type_2_normalized_incident_rate, … crime_type_N_count, crime_type_N_normalized_incident_rate

to be consistent with the other datasets on odn.data.socrata.com but @aaasen  can comment further.

**Comment by chrismetcalf** [comment]
I can see if I can make that work. My FME job crashed last night after literally running my machine out of memory and swap space, so I’m going to probably have to set it up on an FME server for tonight. 

On February 27, 2016 at 8:41:19 AM, zang0 (notifications@github.com) wrote:

slack convo - OK here’s the proposed schema that I’ll be loading into: https://odn.data.socrata.com/dataset/Crime-Statistics-Aggregate-by-Year-Month-and-City/b9cw-c7zm

I combined all of the US Census “Places” Tiger LINE data files to get nationwide set of city polygons

From the listing of agency datasets I then pull down all of the agency instance data, and check to see if it has an incident location or not. If it doesn’t have an incident location, I use the center point provided for the agency. Then I intersect that against my city polygons, discard anything that falls outside a city, discard anything without a date, truncate the datetime to just year-month, aggregate it by geo, incident_parent_type, and date time, and plop it in that dataset

That’s a sample set of data based off just the first 100 rows for the first 50 agencies.

fantastic! are you thinking a follow up FME job to transform this dataset into comparable forms of our other datasets? I’m presuming we want to get to something w/ column names like:

id, name, type, year, month, crime_type_1_count, crime_type_1_normalized_incident_rate, crime_type_2_count, crime_type_2_normalized_incident_rate, … crime_type_N_count, crime_type_N_normalized_incident_rate

to be consistent with the other datasets on odn.data.socrata.com but @aaasen can comment further.

**Comment by aaasen** [comment]
Also from Slack, the best data schema would be something like this:

```
id, name, type, year, month, crime_type, crime_count, crime_rate
```

Since this would allow us to use the current charting and mapping code without any modification.

**Comment by chrismetcalf** [comment]
Cool, that would actually be easier since it requires one less pivot. 

`id` is the city ID, right? `name` would be the city name, and `type` should be “city”?

On February 27, 2016 at 1:57:10 PM, Lane Aasen (notifications@github.com) wrote:

Also from Slack, the best data schema would be something like this:

id, name, type, year, month, crime_type, crime_count, crime_rate

Since this would allow us to use the current charting and mapping code without any modification.

**Comment by aaasen** [comment]
`id` is the ACS ID, `name` is the city name e.g. `Seattle, WA`, and `type` should be `place`.

**Comment by chrismetcalf** [comment]
Got the workflow working earlier this evening, and I think I've got something that'll satisfy @aaasen's needs. Here's a sample with the first 15 records from each agency: https://odn.data.socrata.com/dataset/National-Crime-Rates-by-City/qm29-xhmz

I've been banging my head for two hours trying to get FME Server to work, in the hopes that I could avoid  running out of system memory like I did last night, but I haven't been able to figure out why my workflow isn't running properly. So I'm going to shut down everything else and hope for the best. :+1:

**Comment by chrismetcalf** [comment]
Hah. Yeah, watched the memory pressure climb quickly enough that it's not going to happen nationwide on my little laptop.

Running now for VA/MD/DC and heading to bed.

**Comment by aaasen** [comment]
Looks great. That will be easy to integrate into the ODN. Hope it all works out!

**Comment by zang0** [comment]
Very cool! Nothing like the wiff of fresh data.

**Comment by chrismetcalf** [comment]
Alright, here's VA/MD/DC for 2015 and later. Take a look and see if it'll work for you:

https://odn.data.socrata.com/dataset/National-Crime-Rates-by-City/qm29-xhmz

Still choking on FME Server, but I made some aggressive optimizations and I can actually run it locally now.

**Comment by zang0** [comment]
Per convo: we need to re-run where data from agencies w/ the words sheriff, sheriffs, sheriff's is NOT included in the analysis. Including causes unfair comparisons.

**Comment by chrismetcalf** [comment]
Had to recreate big chunks of my workflow last night since FME and Git got in a fight over who was right. I should have something running soon though.

**Comment by chrismetcalf** [comment]
https://odn.data.socrata.com/dataset/National-Police-Department-Crime-Rates-by-Month-Ye/tt5s-y5fc

Police only data!

**Comment by chrismetcalf** [comment]
Yearly roll-up of the same: https://odn.data.socrata.com/dataset/National-Police-Department-Crime-Rates-By-Year-Cit/yd3b-aji3

**Comment by aaasen** [comment]
Cool! I'll integrate these when I get out of class at 11:30.

**Comment by chrismetcalf** [comment]
It looks like its also fixed the duplicate Washington DCs thing, at least for DC's ID

**Comment by zang0** [comment]
closing this. we'll open a new on for the v.data.3 pipe changes.
