### ISSUE TITLE
'no follow' all +comparison links for N^2 location pages

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#273]
so we're not seeing a significant increase in traffic despite huge jumps in indexed pages. looks like the bots following way more than n^2 location permutations. 

see google email below. here's an example: http://www.opendatanetwork.com/region/0500000US28049-0500000US01125-0500000US22079-0500000US22017-0500000US12033-0500000US22073/Hinds_County_MS-Tuscaloosa_County_AL-Rapides_Parish_LA-Caddo_Parish_LA-Escambia_County_FL-Ouachita_Parish_LA/population

bot's on a bit of a wild goose chase. think we'll need to add no follows from all the N^2 pages so the bot never gets into the N^3, N^4 ... pages.

--

Message type: [WNC-788701]
Search Console

High number of URLs found on http://www.opendatanetwork.com/

To: webmaster of http://www.opendatanetwork.com/,

Googlebot identified a significant increase in the number of URLs found on http://www.opendatanetwork.com/. This makes it harder to crawl the website and can result in users not finding your site's fresh content in search. Googlebot may unnecessarily be crawling a large number of distinct URLs that point to identical or similar content, or crawling parts of your site that are not intended to be crawled by Googlebot. As a result Googlebot may consume much more bandwidth than necessary, or may be unable to completely index all of the content on your site.
Recommended actions:
1	

Identify redundant URL patterns

Review the list of sample URLs below to find common patterns such as: login-protected pages, RSS feeds not made for web-search, search result pages or unnecessary tag pages, or product listing pages with unnecessary filtering parameters.
2	

Review URL parameters

The URL parameter handling tool can sometimes help to resolve issues like this. If your site uses URL parameters, check the settings in Search Console, and adjust them where needed.
	
Check URL parameters
3	

Fix the root cause

This issue can be caused by a number of different factors. You may need to get help from your web-developer to properly diagnose, reduce, or resolve this problem on your website. Use the help center articles linked below as a guide.
Need more help?
•	See the Googlebot encountered an extremely high number of URLs on your site Help Center article.
•	Tell Google about your duplicate content with the URL parameter handling tool.
•	Use canonical URLs.
•	See the Use rel="nofollow" for specific links to simplify crawling, and learn about robots.txt files to block.
•	Ask questions in our forum for more help - mention message type [WNC-788701].
List of sample URLs

http://www.opendatanetwork.com/region/0500000US02050-0500000US53049-0500000US30053-0500000US41031-0500000US53039-0500000US53055-0500000US16049/Bethel_Census_Area_AK-Pacific_County_WA-Lincoln_County_MT-Jefferson_County_OR-Klickitat_County_WA-San_Juan_County_WA-Idaho_County_ID/health/excessive_drinking_rate

http://www.opendatanetwork.com/region/0500000US02180-0500000US16009-0500000US02261-0500000US53043-0500000US02220-0500000US16021-0500000US02185/Nome_Census_Area_AK-Benewah_County_ID-Valdez-Cordova_Census_Area_AK-Lincoln_County_WA-Sitka_City_and_Borough_AK-Boundary_County_ID-North_Slope_Borough_AK/education

http://www.opendatanetwork.com/region/0500000US05031-0500000US05045-0500000US29031-0500000US47119-0500000US01077-0500000US29097/Craighead_County_AR-Faulkner_County_AR-Cape_Girardeau_County_MO-Maury_County_TN-Lauderdale_County_AL-Jasper_County_MO/health/excessive_drinking_rate

http://www.opendatanetwork.com/region/0500000US05051-0500000US05031-0500000US05045-0500000US48037-0500000US40101/Garland_County_AR-Craighead_County_AR-Faulkner_County_AR-Bowie_County_TX-Muskogee_County_OK/population

http://www.opendatanetwork.com/region/0500000US05125-0500000US40145-0500000US29043-0500000US28033-0500000US05045-0500000US48037-0500000US28121-0500000US22015/Saline_County_AR-Wagoner_County_OK-Christian_County_MO-DeSoto_County_MS-Faulkner_County_AR-Bowie_County_TX-Rankin_County_MS-Bossier_Parish_LA/health/access_to_exercise_opportunities_rate

http://www.opendatanetwork.com/region/0500000US08001-0500000US49057-0500000US49035-0500000US08123-0500000US08031-0500000US08059-0500000US08101/Adams_County_CO-Weber_County_UT-Salt_Lake_County_UT-Weld_County_CO-Denver_County_CO-Jefferson_County_CO-Pueblo_County_CO/earnings

http://www.opendatanetwork.com/region/0500000US09007-0500000US34019-0500000US09005-0500000US36091-0500000US44009-0500000US33013-0500000US34037-0500000US25001/Middlesex_County_CT-Hunterdon_County_NJ-Litchfield_County_CT-Saratoga_County_NY-Washington_County_RI-Merrimack_County_NH-Sussex_County_NJ-Barnstable_County_MA/health/physical_inactivity_rate/2015

http://www.opendatanetwork.com/region/0500000US12105-0500000US12111-0500000US12081-0500000US12097/Polk_County_FL-St._Lucie_County_FL-Manatee_County_FL-Osceola_County_FL/job_proximity

http://www.opendatanetwork.com/region/0500000US28049-0500000US01125-0500000US22079-0500000US22017-0500000US12033-0500000US22073/Hinds_County_MS-Tuscaloosa_County_AL-Rapides_Parish_LA-Caddo_Parish_LA-Escambia_County_FL-Ouachita_Parish_LA/population

http://www.opendatanetwork.com/region/0500000US28049-0500000US01125-0500000US22079-0500000US22073-0500000US01101-0500000US12033-0500000US48423-0500000US01097/Hinds_County_MS-Tuscaloosa_County_AL-Rapides_Parish_LA-Ouachita_Parish_LA-Montgomery_County_AL-Escambia_County_FL-Smith_County_TX-Mobile_County_AL/job_proximity

http://www.opendatanetwork.com/region/0500000US28049-0500000US22017-0500000US22079-0500000US01125-0500000US22073-0500000US22105-0500000US22033-0500000US12033/Hinds_County_MS-Caddo_Parish_LA-Rapides_Parish_LA-Tuscaloosa_County_AL-Ouachita_Parish_LA-Tangipahoa_Parish_LA-East_Baton_Rouge_Parish_LA-Escambia_County_FL/environmental_health

http://www.opendatanetwork.com/region/0500000US28049-0500000US22017-0500000US22079-0500000US22033-0500000US01097-0500000US01101-0500000US12033/Hinds_County_MS-Caddo_Parish_LA-Rapides_Parish_LA-East_Baton_Rouge_Parish_LA-Mobile_County_AL-Montgomery_County_AL-Escambia_County_FL/health/physical_inactivity_rate

http://www.opendatanetwork.com/region/0500000US28089-0500000US28121-0500000US05125-0500000US22005-0500000US48397-0500000US12113/Madison_County_MS-Rankin_County_MS-Saline_County_AR-Ascension_Parish_LA-Rockwall_County_TX-Santa_Rosa_County_FL/occupations

http://www.opendatanetwork.com/region/0500000US29189-0500000US20091-0500000US21111-0500000US17119-0500000US39061-0500000US17167-0500000US29095-0500000US17163/St._Louis_County_MO-Johnson_County_KS-Jefferson_County_KY-Madison_County_IL-Hamilton_County_OH-Sangamon_County_IL-Jackson_County_MO-St._Clair_County_IL/health/excessive_drinking_rate/2015

http://www.opendatanetwork.com/region/0500000US33001-0500000US50023-0500000US36043-0500000US33005-0500000US36021-0500000US36053-0500000US50021-0500000US25011/Belknap_County_NH-Washington_County_VT-Herkimer_County_NY-Cheshire_County_NH-Columbia_County_NY-Madison_County_NY-Rutland_County_VT-Franklin_County_MA/health/physical_inactivity_rate/2015

http://www.opendatanetwork.com/region/0500000US35049-0500000US08101-0500000US06079-0500000US04025-0500000US04005-0500000US48303/Santa_Fe_County_NM-Pueblo_County_CO-San_Luis_Obispo_County_CA-Yavapai_County_AZ-Coconino_County_AZ-Lubbock_County_TX/health/excessive_drinking_rate

http://www.opendatanetwork.com/region/0500000US40131-0500000US40017-0500000US40037-0500000US29037-0500000US20015/Rogers_County_OK-Canadian_County_OK-Creek_County_OK-Cass_County_MO-Butler_County_KS/occupations

http://www.opendatanetwork.com/region/0500000US48113-0500000US48453-0500000US40109-0500000US48121-0500000US48439-0500000US48423-0500000US48309-0500000US40143/Dallas_County_TX-Travis_County_TX-Oklahoma_County_OK-Denton_County_TX-Tarrant_County_TX-Smith_County_TX-McLennan_County_TX-Tulsa_County_OK/health/physical_inactivity_rate/2015

http://www.opendatanetwork.com/region/0500000US48439-0500000US48113-0500000US48121-0500000US40143-0500000US48139-0500000US48085-0500000US48027/Tarrant_County_TX-Dallas_County_TX-Denton_County_TX-Tulsa_County_OK-Ellis_County_TX-Collin_County_TX-Bell_County_TX/health/physical_inactivity_rate/2015

http://www.opendatanetwork.com/region/0500000US48439-0500000US48113-0500000US48121-0500000US48085-0500000US48453-0500000US48423/Tarrant_County_TX-Dallas_County_TX-Denton_County_TX-Collin_County_TX-Travis_County_TX-Smith_County_TX/health/excessive_drinking_rate

http://www.opendatanetwork.com/region/0500000US49005-0500000US49057-0500000US16019-0500000US08069-0500000US16083-0500000US16027/Cache_County_UT-Weber_County_UT-Bonneville_County_ID-Larimer_County_CO-Twin_Falls_County_ID-Canyon_County_ID/population

http://www.opendatanetwork.com/region/0500000US49021-0500000US08085-0500000US08067-0500000US06033/Iron_County_UT-Montrose_County_CO-La_Plata_County_CO-Lake_County_CA/health/access_to_exercise_opportunities_rate

http://www.opendatanetwork.com/region/0500000US50025-0500000US36031-0500000US33003-0500000US36025-0500000US42115-0500000US23013-0500000US44001-0500000US36107/Windham_County_VT-Essex_County_NY-Carroll_County_NH-Delaware_County_NY-Susquehanna_County_PA-Knox_County_ME-Bristol_County_RI-Tioga_County_NY/health/adult_smoking_rate

http://www.opendatanetwork.com/region/0500000US54003-0500000US24015-0500000US42001-0500000US24043-0500000US42075/Berkeley_County_WV-Cecil_County_MD-Adams_County_PA-Washington_County_MD-Lebanon_County_PA/occupations

http://www.opendatanetwork.com/region/0500000US56013-0500000US31157-0500000US31111-0500000US56037-0500000US16011-0500000US31019-0500000US49003/Fremont_County_WY-Scotts_Bluff_County_NE-Lincoln_County_NE-Sweetwater_County_WY-Bingham_County_ID-Buffalo_County_NE-Box_Elder_County_UT/health

http://www.opendatanetwork.com/region/0500000US56021-0500000US08077-0500000US49045-0500000US08014-0500000US49057-0500000US08013-0500000US46103-0500000US31153-0500000US08045/Laramie_County_WY-Mesa_County_CO-Tooele_County_UT-Broomfield_County_CO-Weber_County_UT-Boulder_County_CO-Pennington_County_SD-Sarpy_County_NE-Garfield_County_CO/health/access_to_exercise_opportunities_rate

http://www.opendatanetwork.com/region/0500000US56021-0500000US08077-0500000US49045-0500000US08123-0500000US49057-0500000US08014-0500000US31153/Laramie_County_WY-Mesa_County_CO-Tooele_County_UT-Weld_County_CO-Weber_County_UT-Broomfield_County_CO-Sarpy_County_NE/occupations

http://www.opendatanetwork.com/region/0500000US56041-0500000US56023-0500000US32001-0500000US49007/Uinta_County_WY-Lincoln_County_WY-Churchill_County_NV-Carbon_County_UT/occupations

http://www.opendatanetwork.com/region/1600000US0205000-1600000US5364365-1600000US5327785-1600000US5319630/Badger_AK-Silverdale_WA-Graham_WA-Eastmont_WA/occupations/law_enforcement

http://www.opendatanetwork.com/region/1600000US1077580-1600000US3649121-1600000US2430325/Wilmington_DE-Mount_Vernon_NY-Frederick_MD/occupations/farming_fishing_foresty

http://www.opendatanetwork.com/region/1600000US2117848-1600000US1838358-1600000US3949840/Covington_KY-Jeffersonville_IN-Middletown_OH/occupations/health_support/2013

http://www.opendatanetwork.com/region/1600000US2686000-1600000US5566000/Westland_MI-Racine_WI/occupations/office_and_administration

http://www.opendatanetwork.com/region/1600000US2706616-1600000US2680700/Bloomington_MN-Troy_MI/occupations/engineering/2013

http://www.opendatanetwork.com/region/1600000US3137000-1600000US2079000-1600000US0804000-1600000US4075000/Omaha_NE-Wichita_KS-Aurora_CO-Tulsa_OK/population/population_change

http://www.opendatanetwork.com/region/1600000US3231900-1600000US0816000-1600000US3502000/Henderson_NV-Colorado_Springs_CO-Albuquerque_NM/occupations/sales/2013

http://www.opendatanetwork.com/region/1600000US3268400-1600000US0832155-1600000US0614218/Sparks_NV-Greeley_CO-Clovis_CA/

http://www.opendatanetwork.com/region/1600000US3410000-1600000US4206088-1600000US1077580-1600000US0950370/Camden_NJ-Bethlehem_PA-Wilmington_DE-New_Britain_CT/earnings/percent_earning_$50000_to_$64999

http://www.opendatanetwork.com/region/1600000US4841464-1600000US4817000-1600000US0654652-1600000US0624680/Laredo_TX-Corpus_Christi_TX-Oxnard_CA-Fontana_CA/occupations/office_and_administration/2013

http://www.opendatanetwork.com/region/1600000US4865000-1600000US0455000-1600000US4824000-1600000US4827000/San_Antonio_TX-Phoenix_AZ-El_Paso_TX-Fort_Worth_TX/education

http://www.opendatanetwork.com/region/1600000US5003175-1600000US3347940-1600000US5004750-1600000US3325300/Barre_VT-Milford_NH-Bennington_VT-Exeter_NH/occupations

http://www.opendatanetwork.com/region/1600000US5004750-1600000US5003175-1600000US4473130-1600000US2355120-1600000US4211232/Bennington_VT-Barre_VT-Wakefield-Peacedale_RI-Old_Orchard_Beach_ME-Carbondale_PA/earnings/median_male_earnings_(full_time)

http://www.opendatanetwork.com/region/1600000US5061225-1600000US2308395-1600000US3629443-1600000US2527100-1600000US3340180/Rutland_VT-Brunswick_ME-Gloversville_NY-Greenfield_Town_MA-Laconia_NH/population

http://www.opendatanetwork.com/region/310M200US12100-310M200US17980-310M200US22180-310M200US11100/Atlantic_City_Metro_Area_(NJ)-Columbus_Metro_Area_(GA-AL)-Fayetteville_Metro_Area_(NC)-Amarillo_Metro_Area_(TX)/occupations/farming_fishing_foresty

http://www.opendatanetwork.com/region/310M200US14740-310M200US35980-310M200US15540-310M200US36500/Bremerton_Metro_Area_(WA)-Norwich_Metro_Area_(CT)-Burlington_Metro_Area_(VT)-Olympia_Metro_Area_(WA)/occupations/media

http://www.opendatanetwork.com/region/310M200US14740-310M200US35980-310M200US15540-310M200US45860/Bremerton_Metro_Area_(WA)-Norwich_Metro_Area_(CT)-Burlington_Metro_Area_(VT)-Torrington_Micro_Area_(CT)/occupations/computers_and_math

http://www.opendatanetwork.com/region/310M200US27860-310M200US25620-310M200US17420-310M200US41140-310M200US48700/Jonesboro_Metro_Area_(AR)-Hattiesburg_Metro_Area_(MS)-Cleveland_Metro_Area_(TN)-St._Joseph_Metro_Area_(MO-KS)-Williamsport_Metro_Area_(PA)/occupations

http://www.opendatanetwork.com/region/310M200US30860-310M200US41100-310M200US22380-310M200US21700/Logan_Metro_Area_(UT-ID)-St._George_Metro_Area_(UT)-Flagstaff_Metro_Area_(AZ)-Eureka_Micro_Area_(CA)/education

http://www.opendatanetwork.com/region/310M200US32580-310M200US12540-310M200US44700-310M200US33700-310M200US23420-310M200US29460-310M200US18580-310M200US47300-310M200US21340/McAllen_Metro_Area_(TX)-Bakersfield_Metro_Area_(CA)-Stockton_Metro_Area_(CA)-Modesto_Metro_Area_(CA)-Fresno_Metro_Area_(CA)-Lakeland_Metro_Area_(FL)-Corpus_Christi_Metro_Area_(TX)-Visalia_Metro_Area_(CA)-El_Paso_Metro_Area_(TX)/gdp/annual_change_in_gdp

http://www.opendatanetwork.com/region/310M200US40380-310M200US44140-310M200US17460-310M200US49340/Rochester_Metro_Area_(NY)-Springfield_Metro_Area_(MA)-Cleveland_Metro_Area_(OH)-Worcester_Metro_Area_(MA-CT)/occupations/healthcare

http://www.opendatanetwork.com/region/310M200US48620-310M200US46140-310M200US10900-310M200US23060-310M200US24340-310M200US45060/Wichita_Metro_Area_(KS)-Tulsa_Metro_Area_(OK)-Allentown_Metro_Area_(PA-NJ)-Fort_Wayne_Metro_Area_(IN)-Grand_Rapids_Metro_Area_(MI)-Syracuse_Metro_Area_(NY)/gdp
Google Inc. 1600 Amphitheatre Parkway Mountain View, CA 94043 | Unsubscribe
Add partners who should receive messages for this Search Console account.

+ @aaasen

**Comment by ToshMeston** [comment]
Added no follow to the links in the Compare Data area when there are 2 or more regions on the page.  Fixed.

**Comment by ToshMeston** [comment]
Added rel="nofollow" to the chart tab links and the map summary links as well as the Compare Data links.  That should be everything.

**Comment by zang0** [comment]
I think we should keep the chart tab links and map summary links open for the N^2 pages. We want queries like 'graduation rate portland vs seattle' just not  'graduation rate portland vs seattle vs san jose'

**Comment by ToshMeston** [comment]
Chart tabs and map summary links will show nofollow when there are 3 or more regions on the page now.

**Comment by zang0** [comment]
looks good.

**Comment by zang0** [comment]
Just realized google's already got a ton of URLs in its purvue, so we need to add noindex to >N^2 pages as well. So if the bot lands on any URL w/ MORE than 2 locations, we want to add the following metatag:

<meta name="robots" content="noindex">

**Comment by ToshMeston** [comment]
Fixed.
