### ISSUE TITLE
2 tier nav fallout tweaks

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#276]
new stuff looks cool. some tweaks that will help a bunch:

_1 change Education top dropdown to say 'Graduation Rate' NOT Education - http://opendatanetwork-staging.herokuapp.com/region/0500000US53033/King_County_WA/education/high_school_graduation_rate/2013?

_2 whenever we have a dropdown w/ only 1 option, just show the text, NOT the actual drop down. example: http://opendatanetwork-staging.herokuapp.com/region/0500000US53033/King_County_WA/earnings/median_earnings/2013?

the 2013 drop down should simply say 2013 in the same text/font format.

_3 population currently looks weird w/ Population repeated twice. Lets change the second drop down options from: 'Population', 'Population Change' to 'Population Count', 'Population Rate of Change' - note: can we do this w/o changing the URLs? We've got some important inbound links including a new mention in Fast Company as well as all the Google links.

_4 can change the 'Production' tab to 'Economy' and include the 'Cost of Living' subcategory currently under the Jobs high level.

_5 can we show years in reverse chrono order. e.g. clicking on '2014' in http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/consumption/annual_change_in_pce/2014? should list in reverse chrono.

_6 can we change options under 'Health' from 'Health Behaviors' and 'Health' to 'Health Behaviors' and 'Health Indicators' 

_7 clicking enter on a menu toggle should select the highlighted entry

_8 all options under the second tab for http://opendatanetwork-staging.herokuapp.com/region/0500000US53033/King_County_WA/occupations/business_and_finance/2013? should be: blah Employment Rate as in 'Business and Finance Employment Rate', 'Computers and Math Employment Rate'

_9 left align the Demographics, Population and 'The population of Seattle ...' texts in http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/population/population/2013?

**Comment by aaasen** [comment]
Fixed everything except part 7 (clicking enter on a menu toggle should select the highlighted entry). It's actually a little hard to do and I don't have time right now. If it is a big deal I can do it but I thought that since we don't have keyboard navigation on these menus it doesn't make all that much sense.

**Comment by zang0** [comment]
not a big deal. closing this. looks great!
