### ISSUE TITLE
not all earnings permutations are red/yellow/green

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#283]
go to:http://opendatanetwork-staging.herokuapp.com/region/0500000US53033/King_County_WA/earnings/median_earnings/2013?

click on top 5 options under 'Median Earnings' - note: they're all correctly stop light colors. Not options >=6 turn blue. should all be stop light colors.

**Comment by aaasen** [comment]
This was intentional. With metrics like median earnings, more is better, less is worse, so we have stop light colors. I don't think the stop light coloring really makes sense with metrics like "Percent Earning $35,000 to $49,999". What is better in that case?

**Comment by zang0** [comment]
good point. i was in a mad test rush. closing.
