### ISSUE TITLE
Wire in front end to crime data

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#285]
splitting up #272 into pipe and front end.

https://odn.data.socrata.com/dataset/National-Crime-Rates-by-City/qm29-xhmz

has 1st pass on crime data per #272 

--

1. user should be able to see a crime map + charts and toggle by type of crime, i.e. assault.
2. user should be able to compare cities (rolled up geo regions will happen post take 1) for which we have crime data (suggested comparison autosuggest is constrained to appropriate datasets)
3. summary stats will be broken down by month going back 36 months
4. crime data needs to be per capita normalized (# incidents / 10K population) - take (#crimes/#people)*10000. Per capita normalization should use our most recent measured data (2013)
5. charts should include timeline data where take 1 includes the sum across all crime types. Take 2 we'll tackle an in chart toggle across all individual crime types
6. for queries corresponding to region/sub-topic, we'll use the data set expansion query terms: crime, police, arrest, warrant

**Comment by aaasen** [comment]
@chrismetcalf @zang0 I need a dataset description as well as an attribution.

**Comment by chrismetcalf** [comment]
Great question. @zang0, any idea how we should attribute the crime data?

**Comment by aaasen** [comment]
Here's a review app with crime maps: https://opendatanetwork-staging-pr-288.herokuapp.com/region/1600000US1150000/Washington_DC/city_crime/theft_count/2015

It's not done yet but it does give us some insight into errors in the data. For example, why are there so few crimes in DC? That doesn't seem right. Also, @chrismetcalf the dots outside of DC/MA/VA seem to be errors with you census ID matching. There aren't that many though.

**Comment by aaasen** [comment]
One more thing: the crime tab will only show up for cities in DC, Maryland, and Virginia. We still need to be careful about not showing cities without data though.

**Comment by chrismetcalf** [comment]
@aaasen Actually I don't think those points crimes listed outside VA/MD/DC are "errors", they're crimes from those agencies that occurred in other jurisdictions. The state showing up wrong is an error though, I pull the state from the agency but get the city from the location of the crime.

**Comment by chrismetcalf** [comment]
@aaasen It looks like somehow I ended up with two sets of data that match the same ID for Washington, DC. Filter https://odn.data.socrata.com/dataset/National-Crime-Rates-By-City-and-Year/xs9q-cg4j by 1600000US1150000 and you'll see what I mean.

**Comment by aaasen** [comment]
Yes, looks like it. https://odn.data.socrata.com/resource/368f-rei5.json?id=1600000US1150000&crime_type=Theft&year=2015

**Comment by zang0** [comment]
Sorry, make that:
Summary crime statistics are generated by an aggregation across month and crime type. Crime incidents whose recorded coordinates are not located inside the US Census based boundary of a given city are not included in summary statistics. Normalization is based on US Census 2013 population counts. Crime rates are normalized on a per 100K basis; specifically, the crime count is divided by the population count, the result is then multiplied by 100k and rounded to the nearest integer value. Crime counts are not available for all cities in the US, and in some cases, policing agencies for a given city may have partial crime type coverage.

Above charts are based on data from CrimeReports.com. Data Source | ODN Dataset | API - i

where DataSource points to:

http://crimereports.socrata.com/#!/dashboard?incident_types=Assault%252CAssault%2520with%2520Deadly%2520Weapon%252CBreaking%2520%2526%2520Entering%252CDisorder%252CDrugs%252CHomicide%252CKidnapping%252CLiquor%252COther%2520Sexual%2520Offense%252CProperty%2520Crime%252CProperty%2520Crime%2520Commercial%252CProperty%2520Crime%2520Residential%252CQuality%2520of%2520Life%252CRobbery%252CSexual%2520Assault%252CSexual%2520Offense%252CTheft%252CTheft%2520from%2520Vehicle%252CTheft%2520of%2520Vehicle&start_date=2016-02-23&end_date=2016-03-01&days=sunday%252Cmonday%252Ctuesday%252Cwednesday%252Cthursday%252Cfriday%252Csaturday&start_time=0&end_time=23&include_sex_offenders=false&lat=47.60802928647356&lng=-122.33379364013672&zoom=15&shapeNames=&show_list=true

and the lat/long is changed to the lat / long of the current city

**Comment by zang0** [comment]
closing this since first pass is done.
