### ISSUE TITLE
generalize dataset search result descriptions to include cat

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#286]
generalize dataset search result descriptions to include category in addition to subcategory

example: 

_1. 

http://opendatanetwork-staging.herokuapp.com/region/0500000US53033/King_County_WA/population/population/2013?

currently says:

176 Population Data Sets Involving King County, WA

should say:

176 Demographics and Population Data Sets Involving King County, WA

_2.

http://opendatanetwork-staging.herokuapp.com/region/0500000US53033/King_County_WA/environmental_health/median_environmental_health_hazard_index/2015?

says:

120 Environment Data Sets Involving King County, WA

should say:

120 Health and Environment Data Sets Involving King County, WA

**Comment by ToshMeston** [comment]
Fixed.  Also changed "Data Set" to "Dataset" to be consistent with with other Socrata properties.
