### ISSUE TITLE
drop case on place in crime dataset

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#287]

**Comment by zang0** [comment]
month and year as number types

**Comment by chrismetcalf** [comment]
@aaasen Would be acceptable to have the yearly counts and rates in a second dataset? That'll be easier to generate and I believe it also will be clearer for developers if we share that one out.

**Comment by aaasen** [comment]
Yes that would work.

**Comment by chrismetcalf** [comment]
Cool. https://odn.data.socrata.com/dataset/National-Crime-Rates-by-City/qm29-xhmz has been updated to have "place" located, and to change the datatypes of `year` and `month`.

**Comment by chrismetcalf** [comment]
And here is the yearly dataset: https://odn.data.socrata.com/dataset/National-Crime-Rates-By-City-and-Year/xs9q-cg4j

`crime_rate` is empty - one I have a good workflow again, I can create a real yearly workflow and add in a crime rate calculation.
