### ISSUE TITLE
chanes for sum of crimes comparisonsg

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#292]
Chatted w/ Kyle. So our current sum across all crime types for cities being compared is not legitimate. The reason is not all cities publish all crime types. The good news is if they publish any crimes for a given crime type, then we can safely presume they publish all crimes for that crime type. So we need to EITHER:

_1 add a crime type drop down for the comparison chart where ONLY crime types that exist for all regions are present

_2 sum all crimes for the intersection of crime types across the compared regions AND state them in the chart notes, something like: Crime counts include the sum of arson, murder, mayem and blood curddling scream inducements. Crime counts do not include any other crimes which may have occurred in the displayed regions.

I think _1 is cleaner.

**Comment by aaasen** [comment]
I took the second approach to avoid having to make a custom UI for this chart. It has a slight impact on the data. Take a look at the explanation above each crime chart. I can tweak that if needed.
