### ISSUE TITLE
autosuggest changes to constrain addable comparisons

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#293]
_1 update autosuggest data set w/ output of crime pipeline

_2 either drop the 5 suggestions entirely OR add walk down the list until you get enough that have data

**Comment by aaasen** [comment]
For 2, decided to fetch 20 similar regions and only include the ones that have data.

Note that a region will appear if it has any data even if it isn't very much. For example, Virginia Beach has just one data point: 

```json
https://odn.data.socrata.com/resource/ee8v-jgb5.json?id=1600000US5182000
[{"crime_count":"1","crime_rate":"0.00000226167078667695","id":"1600000US5182000","incident_parent_type":"Other","month":"2","name":"Virginia Beach, VA","year":"2016"}]
```

I think these problems should be fixed when the dataset is generated, not by the frontend.

**Comment by zang0** [comment]
Looks like I can still in the text box search for things which do not have crime data.

**Comment by aaasen** [comment]
Can you give me an example? The map may not show all regions if they do not all have theft data.

**Comment by zang0** [comment]
My mistake, looks like its not that they have no data. But many have extremely little. See:

Severn MD in:

http://opendatanetwork-staging.herokuapp.com/region/1600000US2407125-1600000US2471150-1600000US2478650/Bethesda_MD-Severn_MD-Travilah_MD/city_crime/assault_rate/2015?

Question: can we assume the no data cases are really just 0 crimes of that type?

**Comment by aaasen** [comment]
We can't constrain the autosuggest based on the crime type selected. I
think that cities with so little data shouldn't be included in the dataset
at all. It's clear that these numbers are not reflective of the true crime
rate. Maybe we could filter out regions with less than 5 reported crimes?
That would get rid of most of the junk.

**Comment by aaasen** [comment]
Added instructions for updating the autosuggest datasets: https://docs.google.com/document/d/1WUv2fIyj3G-7L5aCPrCTzsPXBJ44_7z6pvj9ALlQWGc/edit#heading=h.xvtua31o46zr
