### ISSUE TITLE
change crime counts to normalized incidents / 100K 

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#295]
_1 Add incident rates per 100k to the map drop down list. The names should also change to stuff like: Traffic Crime Incident Rate

Note: we likely want to also add a drop down between Rates/Counts OR mix the two into the same crime type drop down. If the latter, we should drop the total number displayed and add a more option.

_2 Add an Incident Rate chart in addition to the counts. If pressed for time and forced to choose, choose incident rate.

**Comment by aaasen** [comment]
The dataset that the maps use does not currently have data for `crime_rate`. Giving this to @chrismetcalf  to fill in that data. It would make the maps a lot more useful.

**Comment by zang0** [comment]
Aren't we using: https://odn.data.socrata.com/dataset/National-Crime-Rates-by-City/qm29-xhmz which is the dataset referenced in the source citation? The crime_rate column is there.

**Comment by chrismetcalf** [comment]
@zang0 We're using a rolled-up dataset I just created with a query in-platform to sum up the crimes by year. I don't think you can just add up the crime rates to get a yearly rate for that roll-up.

**Comment by zang0** [comment]
per chat, @chrismetcalf to regenerate w/ both count + rates.

**Comment by zang0** [comment]
Note: I changed _1 in the original description as I think we actually want both counts and rates in the map.

**Comment by zang0** [comment]
new data to take out for a spin @ https://odn.data.socrata.com/dataset/National-Police-Department-Crime-Rates-By-Year-Cit/yd3b-aji3 per #272

**Comment by aaasen** [comment]
On staging: http://opendatanetwork-staging.herokuapp.com/region/1600000US1150000/Washington_DC/city_crime/theft_count/2015?

I used `crimes / month / 100k` as the unit - anyone have other suggestions?

**Comment by zang0** [comment]
closing, looks good.
