### ISSUE TITLE
+ gray comment rectangle under map for crimes

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#296]
Note: Cities often report crimes for a subset of crime types. As a result, cities may appear or disappear from the map for a given crime type selection. The absence of a city should not be interpreted as the absence of the specified crime type.

@aaasen Note: I don't think we need to crop the crime type permutations as a result, but if you're still feeling it, feel free.

**Comment by aaasen** [comment]
Did not crop the crime types. Very easy to do if we want to though.
