### ISSUE TITLE
drop down should only contain crime types for which the target city has data

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#298]
ex: http://opendatanetwork-staging.herokuapp.com/region/1600000US5166672/Reston_VA/city_crime/theft_count/2015?

Note: Only 'Theft from Vehicle Count' has any crimes. The user in this case shouldn't be able to see the other crime type pivots as their city of interest is not involved.

**Comment by zang0** [comment]
After sniffing a little closer, looks like the crime type should have a count > 10 else we should not include the type. Seeing suspicious stuff on the low end like: 

http://opendatanetwork-staging.herokuapp.com/region/1600000US2407125/Bethesda_MD/city_crime/theft_count/2015?

bethesda md, has a theft count = 1, but a theft from vehicle count of 389. Lets see if that helps out some of the suspects.

**Comment by aaasen** [comment]
Requiring a crime type to have a count of 10 for each city shown restricted the types too much. Threshold is at 1 right now.
