### ISSUE TITLE
crime descriptions should be in gray rectangles below the charts

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#302]
stuff like verbage below for http://opendatanetwork-staging.herokuapp.com/region/1600000US2407125-1600000US2441250-1600000US1150000/Bethesda_MD-Hyattsville_MD-Washington_DC/city_crime/theft_count/2015?

should go in gray rectangles below the chart so we stick w/ our chart descriptions ui paradigm.

--

Crimes reported per month per 100,000 people. Only crime types that are reported by every selected city are shown. For the selected regions, the following crime types are available: Drugs, Assault, Breaking & Entering, Robbery, Traffic, Theft of Vehicle, Theft from Vehicle, Theft, Other, Community Policing.

**Comment by ToshMeston** [comment]
Fixed.
