### ISSUE TITLE
move standard schemas stuff below the summary table

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#304]
http://opendatanetwork-staging.herokuapp.com/dataset/lives.data.socrata.com/ntj2-kt9x

note: 

Standard Schemas

Together with the open blah blah stuff off to the right. Move this below the table and fix the width such that it doesn't run super wide like now.

**Comment by ToshMeston** [comment]
Move the schemas section under the table and cleaned up the styles and markup a little bit.
Fixed.
