### ISSUE TITLE
crime type display sentence and mouseover discrepancies

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#308]
no nlg summary sentence and mouse over windows have the wrong crime type:

http://opendatanetwork-staging.herokuapp.com/region/1600000US1150000-1600000US2407125-1600000US2419125/Washington_DC-Bethesda_MD-Columbia_MD/city_crime/fire_count/2015?

**Comment by aaasen** [comment]
This will only happen if there is no data for the given city. Should not be an issue since #298.
