### ISSUE TITLE
pull crime type definitions from dataset and include in more information

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#309]
Can we pull the crime type definitions from: https://odn.data.socrata.com/Government/Crime-Reports-Incident-Type-Descriptions/ny8r-ukmq

and add them under the 'more information' that currently has the type links. so would look something like:

Traffic Count - A violation of traffic law or code
Breaking & Entering Count - blah blah
Assault Count - blah blah

but leave the links intact.

**Comment by zang0** [comment]
punt

**Comment by ToshMeston** [comment]
Fixed.
