### ISSUE TITLE
lots of ie stuff broken

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#310]
looks like a lot of IE stuff isn't working, though i'm using a weird browser simulator, v11 IE on Win 10. Can you bang around and see? For me the following fails:

_1 all autosuggest
_2 region page charts not rendering. see attached screen shot
<img width="1212" alt="screen shot 2016-03-02 at 8 41 37 pm" src="https://cloud.githubusercontent.com/assets/1051776/13484922/3795d0ec-e0b7-11e5-99cc-0cff9ce4d525.png">

**Comment by aaasen** [comment]
That seems to have fixed the IE issues. Accidentally took the browser polyfill out during development since it obfuscates tracebacks. All good now.
