### ISSUE TITLE
tweak title tags to align w/ detailed drop downs

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#314]
_1

for

http://www.opendatanetwork.com/region/1600000US2407125/Bethesda_MD/city_crime/assault_rate/2015?

current title tag is:

<title>Crime Data for Bethesda, MD on the Open Data Network</title>

should be:

<title>Assault Rate for Bethesda, MD - Crime on Open Data Network</title>

_2

for

http://www.opendatanetwork.com/region/1600000US2407125-1600000US2467675/Bethesda_MD-Rockville_MD/city_crime/robbery_rate/2015?

current title tag is

<title>Crime Data for Bethesda, MD and Rockville, MD on the Open Data Network</title>

should be

<title>Robbery Rate for Bethesda, MD and Rockville, MD - Crime on Open Data Network</title>

**Comment by ToshMeston** [comment]
Fixed.

**Comment by zang0** [comment]
looks good! this should help a bunch for SEO.
