### ISSUE TITLE
mobilification

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#317]
![screen shot 2016-03-07 at 2 03 44 pm](https://cloud.githubusercontent.com/assets/1051776/13584894/70914eda-e46d-11e5-86df-a640989be750.png)

**Comment by zang0** [comment]
I think we're close enough to start some more mobile friendly pages. Lets start w/ the region pages and then hit the HP, as folks are landing on those a fair amount. Re: region pages, what I'm thinking is:

_1 when you shrink to within mobile range, 
_1.1 the entire left column disappears
_1.2 the ODN icon shrinks way down to just the icon part minus the text
_1.3 the nav menu gets more compact somehow

@erhodes87 Can you take a look?

re: homepage:

_1 just the icon, search bar, and then a long vertical scroll through the geo regions and categories. I think we could just interleave them somehow so we don't only get category clicks (we're trying to feature the region pages)

**Comment by erhodes87** [comment]
Yep! i'd love to start getting into mobile for these. Do you have a deadline when you'd like them by? 

I'm thinking for the homepage, we may consider doing the icons in a side scroll or dropdowns menu so the geo regions are more of a direct focus. Just an idea. Maybe you can take a look again at the original sketches. I know some things have changed since these were done, but maybe you can let me know if you have any direct feedback to how these were working.
 
[ODN-mobile_sketch.pdf](https://github.com/socrata/opendatanetwork.com/files/166188/ODN-mobile_sketch.pdf)

**Comment by zang0** [comment]
can you pop some time on the calendar in the next few days and lets chat about it. M @ 2PM works.

**Comment by zang0** [comment]
Some homepage feedback for new design, specifically, moving things above the fold:

" The home page doesn't really tell me what to do. I suggest updating it to have the following above the fold:
    search for data
    browse by category
    explore data for a city, county or region
    compare two or more cities, counties or states 
    What is the ODN? (link to a landing page with the video embedded)
"

**Comment by erhodes87** [comment]
I was able to compress some of the data on the homepage, but let me know if you'd still like the "what is ODN" portion linked on the bottom of the page. 

here is the mock up of the homepage:
https://www.dropbox.com/s/mw9vst9qkb8hnr4/mobile-ODN-home.psd?dl=0

with an example of how the search dropdown would look:
https://www.dropbox.com/s/ir3leh5c2fxizfj/mobile-ODN-home_searchdropdown.png?dl=0

with an example of how the category drop down would work:
https://www.dropbox.com/s/tx2drojmz0pqu17/mobile-ODN-home_category.png?dl=0


And then a mock up of the search results (this one uses pretty similar navigation to what we are currently using, with the addition of a "side swipe" to get to the top level categories):
https://www.dropbox.com/s/j9imkn6ryo33oaa/mobile-ODN-results.psd?dl=0


And an alternate version of navigation, trying something a little different:
https://www.dropbox.com/s/nd2u3yww33qdwh9/mobile-ODN-results_V2.psd?dl=0

with an example of how the quicklinks would look:
https://www.dropbox.com/s/kcf10f76d49paqe/mobile-ODN-results_V2_quicklinks.png?dl=0

with an example of what would happen if you clicked on "Demographics":
https://www.dropbox.com/s/t8kf3tpl1jqk58a/mobile-ODN-results_V2_2.png?dl=0

with an example of what it would look like if you clicked on "GDP":
https://www.dropbox.com/s/q6umt90xp7j3jmn/mobile-ODN-results_V2_3.png?dl=0

the thinking behind this navigation would be that if you were to select any of the options (lets just say you start with GDP), it would open a screen that would allow you first to pick something new for that category (example: GDP, Business, etc). If you select something new (lets say business), then the navigation pop up would go to the next level of navigation (Business and Finance) and require you to chose until you've made a selection through all the categories. If someone was to select lets say "2013", then they would only need to select from that category and it would adjust the results. Let me know if that makes sense to you. 

I'm happy to jump on a call if its easier to understand.

**Comment by erhodes87** [comment]
Just checking back on this project. No rush but wanted to know if you had any questions for me or changes i could implement on the mock ups?

**Comment by erhodes87** [comment]
here are the new mock ups based on our conversation:

Home screen (notes: the category drop down shows all categories, all states will be listed with openable fields including 10 metro/county/city names for each) https://www.dropbox.com/s/pn05nhr0jbcikhd/mobile-ODN-home_V2.psd?dl=0

Results page 
https://www.dropbox.com/s/lipd45j94h972j6/mobile-ODN-results_V3.psd?dl=0
notes: all changeable information will be within the refine results button which looks like this:
https://www.dropbox.com/s/xf4d6116f3knocl/mobile-ODN-results_V3_refine.png?dl=0
With each category as a drop down section

Data set results
https://www.dropbox.com/s/ayfoyjvdqyp4urx/mobile-ODN-dataset.psd?dl=0

Data set detail (notes: the chart will side scroll while the rest of the page remains in place)
https://www.dropbox.com/s/r64p90msihkxzrq/mobile-ODN-details.psd?dl=0

if you have any questions or changes let me know.

**Comment by zang0** [comment]
How are the revisions based on our convo coming?

**Comment by zang0** [comment]
Sorry, spaced this was done. Looks good! To @ToshMeston to begin implementation.

**Comment by zang0** [comment]
punting to v.data.5

**Comment by zang0** [comment]
closing this out. smaller issues now in individual tickets
