### ISSUE TITLE
Add NLG Sentence for everywhere we have predictions

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#321]
_1 this includes population, GDP and consumption (e.g. http://www.opendatanetwork.com/region/0400000US53/Washington/consumption/personal_consumption_expenditure/2014?)

_2 lets include all configuration info (i.e. the surrounding text and formulas) near/in the chart configuration that includes whether predictions are made

_3 lets just append sentences for additionally compared regions as we do in our other NLG scenarios.

Example:

http://opendatanetwork-staging.herokuapp.com/region/1600000US5363000/Seattle_WA/population/population/2013?

Lets add text above the population chart w/ the predictions to say:

`The last measured $chart_title for $region_name was $y_last(Measured). $region_name experienced an average annual growth rate of round(100*(1-($y_first(Measured)./$y_last(Measured)))) from our first $chart_title statistic recorded in $x_first. If past trends continue, we forecast the $chart_title to be y_last(Forecasted) by x_last(Forecasted).`

Ex:

The last measured population for King County, WA was 624,681. King County, WA experienced an average annual growth rate of 4.9% from our first population statistic recorded in 2009. If past trends continue, we forecast the population to be 2,119,291 by 2018.

**Comment by ToshMeston** [comment]
Fixed.

**Comment by zang0** [comment]
Few issues:

_1 the content needs to be bot visible, currently its not in the HTML

_2 for an url like: http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/gdp/gdp_per_capita/2013?

can we incorporate the chart description: 

Real (inflation adjusted) GDP per Capita over time.

into the 1 gray text box. Perhaps 

_3 http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/cost_of_living/all/2013?

_3.1 No generated text appears for all the plots w/ forecasts.

_3.2 The generated text is off for cost of living. We should change the second drop down from:

All
Goods
Rents
Other

to

Overall Cost of Living
Cost of Goods
Cost of Rents
Other Costs

_3.2.1

so the top sentence should read:

The overall cost of living of Seattle Metro Area (WA) in 2013 was 107.1.

NOT

The all of Seattle Metro Area (WA) in 2013 was 107.1.

_3.2.2

and the generated plot text should read:

The last measured overall cost of living for Seattle Metro Area (WA) was 101.0. Seattle Metro Area (WA)

NOT

The last measured index for Seattle Metro Area (WA) was 101.0. Seattle Metro Area (WA)

**Comment by ToshMeston** [comment]
Move the forecast descriptions to the server.  Fixed.

**Comment by zang0** [comment]
Looks good!
