### ISSUE TITLE
investigate pop rate of change data

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#327]
cam pointed out that the pop rate of change data seems suspicious. we often have a phenomenon between 2010 and 2011 that doesn't look reflected in the actual pop values. any explantations?

http://www.opendatanetwork.com/region/310M200US41940-310M200US41860-310M200US14860-310M200US41740-310M200US19820-310M200US39580/San_Jose_Metro_Area_(CA)-San_Francisco_Metro_Area_(CA)-Bridgeport_Metro_Area_(CT)-San_Diego_Metro_Area_(CA)-Detroit_Metro_Area_(MI)-Raleigh_Metro_Area_(NC)/population/population/2013?

**Comment by aaasen** [comment]
The only issue that I see here is that both San Jose and Raleigh are displayed in dark blue. The data looks fine as far as I can tell. I should clarify that 2010 on the population change chart means percent change from 2009 to 2010.

**Comment by zang0** [comment]
Ok. Perhaps the issue is that the percent change feels like it would be reflected in the row count numbers, but I think they're so small that they don't really bend the plot much. Closing.
