### ISSUE TITLE
add type for georegions in autosuggest

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#330]
feedback: "It's unclear to me why every major city has both a city and an area in various autosuggest fields. "

**Comment by aaasen** [comment]
Took a first pass at this using the same UI that we use to show the domain of a dataset. 

<img width="537" alt="screen shot 2016-03-12 at 8 09 59 am" src="https://cloud.githubusercontent.com/assets/1320603/13723955/e0e72e74-e829-11e5-9945-25992287ac08.png">

The names used for each type can be tweaked in [constants.js](https://github.com/socrata/opendatanetwork.com/blob/staging/src/constants.js#L16) and the content of the autosuggest menu can be changed in [autosuggest-multi.js](https://github.com/socrata/opendatanetwork.com/blob/staging/src/data/autosuggest-multi.js).

**Comment by zang0** [comment]
looks good. closing.
