### ISSUE TITLE
edu stats not working for counties in WA

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#339]
Looks like none of the counties in Washington, and only Washington are rendering in the map. The line plots look ok. Looks like it is because none (of those I checked) have a 2014 date, which is the last measured date.

repro:

_1 got to a WA state county like:

http://opendatanetwork-staging.herokuapp.com/region/0500000US53027/Grays_Harbor_County_WA/classroom_statistics/student_teacher_ratio/2014?

_2 note: the map has no WA counties

_3 note: the line plot looks fine.

_4 note: 2013 toggle looks fine, but some other states are then not present. 

Fix:

_1. Lets change the default year when no data is present for the specified geo-region? so:

http://opendatanetwork-staging.herokuapp.com/region/0500000US53055/San_Juan_County_WA/classroom_statistics

forwards to:

http://opendatanetwork-staging.herokuapp.com/region/0500000US53055/San_Juan_County_WA/classroom_statistics/student_teacher_ratio/2013?

instead of

http://opendatanetwork-staging.herokuapp.com/region/0500000US53055/San_Juan_County_WA/classroom_statistics/student_teacher_ratio/2014?

_2. Can we not allow the user to select years with missing data but inform them somehow that data is missing?

**Comment by aaasen** [comment]
New behavior:

If a year with no data is selected but there are other years that have data, the user will be redirected to the most recent year with data.
Any regions that don't have data for the given year will have a tooltip that says something like "no data for the given year, click on another region or go to another year".

Also fixed the gap in the line chart.
