### ISSUE TITLE
if autosuggest is failing, remove the 'compare this data' text box 

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#345]

**Comment by ToshMeston** [comment]
Fixed.  We will not show the Compare This Data textbox if peers is dead.

**Comment by zang0** [comment]
actually i was referring to if the autosuggest calls are not returning sucessfully. to be expicit, if this call:

https://odn.data.socrata.com/views/864v-r7tf/columns/category/suggest/seattle?size=5

doesn't return a 200,

do not render the text box.

re: peers service, I thought we already do not render the 5 recommendations if it is not available, if not, we should fall back this way.

**Comment by ToshMeston** [comment]
@zang0 Which textbox?  On the main search bar or the "Compare this Data" textbox?

**Comment by zang0** [comment]
just the "Compare this Data" textbox

**Comment by ToshMeston** [comment]
Remove logic to hide Compare This Data" textbox if peers is down.  Also, we decided to not add a new request to /suggest before rendering to check if the service is down as there are a whole bunch of requests before rendering already.

Fixed or punted.
