### ISSUE TITLE
click activated tooltip in map does not respond to dropdowns

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#346]
_1 goto: http://opendatanetwork-staging.herokuapp.com/region/1600000US2407125/Bethesda_MD/city_crime/assault_rate/2015?

_2 change assault rate drop down to theft rate

note: the tooltip changes correctly

_3 click on a city like columbia

_4 now change theft rate back to assault rate

note: the click activated tool tip did not respond

**Comment by ToshMeston** [comment]
Per the discussion in today's meeting, we decided to just close the user opened popups when the sub-category is changed.  Fixed.

**Comment by zang0** [comment]
I thought we also agreed to collapse the drop down after a click.

**Comment by ToshMeston** [comment]
Fixed.
