### ISSUE TITLE
html leaking into health pages

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#347]
http://opendatanetwork-staging.herokuapp.com/region/0500000US53033-0500000US41005-0500000US53001/King_County_WA-Clackamas_County_OR-Adams_County_WA/health/adult_obesity_rate/2015?

see html tags in text below:

Adult Smoking is the percentage of the adult population that currently smokes every day or most days and has smoked at least 100 cigarettes in their lifetime. <br /><br /> Adult Obesity is the percentage of the adult population (age 20 and older) that reports a body mass index (BMI) greater than or equal to 30 kg/m^2. <br /><br /> Physical Inactivity is the percentage of adults aged 20 and over reporting no leisure-time physical activity. Examples of physical activities provided include running, calisthenics, golf, gardening, or walking for exercise. <br /><br /> Access to Exercise Opportunities measures the percentage of individuals in a county who live reasonably close to a location for physical activity. Locations for physical activity are defined as parks or recreational facilities. Individuals who reside in a census block within half a mile from a park, reside in an urban census tract within one mile of a recreational facility, or reside in a rural census tract within three miles of a recreational facility are considered to have adequate access for opportunities for physical activity. <br /><br /> Excessive Drinking is the percentage of adults that report either binge drinking, defined as consuming more than 4 (women) or 5 (men) alcoholic beverages on a single occasion in the past 30 days, or heavy drinking, defined as drinking more than one (women) or 2 (men) drinks per day on average.

**Comment by ToshMeston** [comment]
Fixed the HTML encoding when spitting out the chart description.  I also removed the bolding on .chart-description since each one of those paragraphs were bold and it looked kind of bad.
