### ISSUE TITLE
Dealing w/ No data for a region for a subcat

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#351]
repro:

_1 go to: http://opendatanetwork-staging.herokuapp.com/region/0500000US53033/King_County_WA/education

_2 note: there is a drop down for classroom statistics, even though no data exists

_3 when i click on it, the system hangs

fix

_1 short term - can we check quickly if data exists. if not, can we show a blown out version of the map like the attached image and say something like:

"No classroom statistics exist for King County in 2014. Try another year, or go to another county on the map by clicking on it."

This should catch most the cases I'm seeing. Longer term, I think we want a watcher process that generates the derived datasets to populate this sort of decision making on its own, so we keep new data additions easy.

![screen shot 2016-03-28 at 6 01 26 pm](https://cloud.githubusercontent.com/assets/1051776/14094870/25a7dfd0-f50f-11e5-8cec-d74537bb9968.png)

**Comment by aaasen** [comment]
Where should we put the "no data exists..." text? I've been experimenting with showing it as a popup but I think it might be better under the map. Also, what should we do if there are two regions selected and only one shows data? If this is implemented as a popup the no data popup can collide with the other region's popup.

**Comment by aaasen** [comment]
System will no longer hang on invalid vectors or vectors without data. Added unit tests to verify this.

**Comment by zang0** [comment]
Few things:

_1 if there is no autosuggest match for the region and data, lets never show the option. so in the king county wa case, there is no autosuggest match in the COMPARE THIS DATA so, the classroom statistics option should never appear

_2 if there exists some data, but not for that year, what you have looks good. 

_3 if one or more regions has data, but 1 does not, then do as you've done, where the region without, shows the popup, but the popup should be killable w/ the x in the right corner
