### ISSUE TITLE
Too many Edu Places Tabs w/ No Data

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#352]
see: http://opendatanetwork-staging.herokuapp.com/region/1600000US2507000/Boston_MA/education_places/public_art?

Note: all but Head Start Centers have no data

Some possible solutions:

_1 Generate a derived data set with a location>column mapping

_2 Query time solution: perhaps we can we use something like this:

https://odn.data.socrata.com/resource/rz8v-4esg.json?$select=count(location)&classification=Head%20Start%20Center&$where=within_circle(location,47.59815,-122.334540,10000)

for every possible classification to see if any results are present. If not, we don't render the drop down. We could cache w/ a long time to live in our own caches so only the first page load is slow. The call seems to be below 200ms most of the time.

**Comment by chrismetcalf** [comment]
So the following will get you a listing of all the classifications that are available in that area:

https://odn.data.socrata.com/resource/rz8v-4esg.json?%24select=classification%2C%20count%28%2A%29&%24where=within_circle%28location%2C47.59815%2C-122.334540%2C10000%29&%24group=classification

You can combine that with an `IN(...)` if you want to limit it to a certain set of classifications.

**Comment by chrismetcalf** [comment]
This will use subselects to just get you a single count of the number of classifications available:

https://odn.data.socrata.com/resource/rz8v-4esg.json?%24query=SELECT%20classification%2C%20count%28%2A%29%20WHERE%20within_circle%28location%2C47.59815%2C-122.334540%2C10000%29%20GROUP%20BY%20classification%20%7C%3E%20SELECT%20COUNT%28%2A%29%20AS%20num_classifications

**Comment by zang0** [comment]
Great! 1 call is way better than 15

**Comment by aaasen** [comment]
Used the call to filter the categories down to the available ones. If the selected category is not available for the selected region, the user is redirected to the classification with the most nearby locations. If no points are near the selected region, all classifications are shown.

**Comment by zang0** [comment]
looks good
