### ISSUE TITLE
redo sitemap to poke google

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#353]
take all regions + all tabs, stack rank by population, and cut off at 50k and resubmit

**Comment by zang0** [comment]
looks like our index went up ~6000 yesterday.

**Comment by zang0** [comment]
Tosh can you take this one? Higher priority than the Moblification. Our promising blip has since faded. Thx.

**Comment by ToshMeston** [comment]
OK.  I put a new on staging.  We need to deploy to submit the URL to Goog.

It contains 50,000 URLs:

- Root
- Join
- Search results for each category
- Search results for each tag
- Search results for each domain
- Top regions for each supported vector sorted by population desc.

**Comment by zang0** [comment]
looks good
