### ISSUE TITLE
add schools from IES to edu places

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#354]
The edu places tab is really thin. Lets include data from:

http://nces.ed.gov/ccd/elsi/tableGenerator.aspx

which has the location of schools across the nation broken down by elementary, middle, etc. Lets make sure to keep the transformers from the IES format into our own. I started the odn-pargen project for this purpose so future updates are easy. Other non place data is there as an example.

This should keep the edu places healthier.

**Comment by aaasen** [comment]
Data should be included in the POI dataset: https://odn.data.socrata.com/dataset/MicroSchemas-Points-of-Interest/ki4q-6ek7

**Comment by zang0** [comment]
Data set created, OUX w/ NBE: https://odn.data.socrata.com/Education/US-Education-Public-Schools/knmi-znhc

ready for mapping into places schema via this ex:

https://github.com/open-data-network/schema-mappings/blob/master/mappings/odn.data.socrata.com/microschemas/points_of_interest-hhs-head-start.yml

**Comment by zang0** [comment]
Mapping added. Data in OBE: https://odn.data.socrata.com/dataset/MicroSchemas-Points-of-Interest/ki4q-6ek7
Being migrated into NBE: https://odn.data.socrata.com/dataset/MicroSchemas-Points-of-Interest/rz8v-4esg

**Comment by zang0** [comment]
fixed
