### ISSUE TITLE
if only 1 region search result, auto forward to the page

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#357]
http://opendatanetwork-staging.herokuapp.com/search?q=98117

note: there is only 1 search result and it is for a region, in this case, just like  in aiutosuggest, lets forward straight to the page.

**Comment by ToshMeston** [comment]
Fixed.  Added test.

**Comment by zang0** [comment]
reopening: works for 1 autosuggest entry left, but not when there is 1 search result (type fast and hit enter before the AS can respond) http://opendatanetwork-staging.herokuapp.com/search?q=king+county+wa

**Comment by zang0** [comment]
never mind, this is because there are search results.
