### ISSUE TITLE
compare autosuggest for expenditures broken

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#362]

**Comment by aaasen** [comment]
Before the autosuggest dataset is updated, you can specify `hasAutosuggest: false` in the data source so that it won't try to fetch an invalid column from autosuggest.

**Comment by zang0** [comment]
@aaasen Is there some way for me to specify that all states should be autosuggested? seems like the autosuggest data set should have some generic support for non sparse data within a specific type.

**Comment by aaasen** [comment]
No there is not. Only way right now is to re-run the autosuggest generation script.
