### ISSUE TITLE
forecast descriptions not respecting pattern

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#364]
go to: http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/education_expenditures/instruction_salaries/2013?

note: 

the $1,438 in this text below is not respecting the pattern in data-sources.js - should be $1,438M
 
The last measured education related capital expenditures for Washington was $1,438. Washington experienced an average annual growth rate of 1.41% from our first education related capital expenditures statistic recorded in 2005. If past trends continue, we forecast the education related capital expenditures to be $1,566 by 2020.

**Comment by ToshMeston** [comment]
Fixed.

**Comment by zang0** [comment]
Fix did not cover the second value, i.e. $1,566 below should be $1,566M

The last measured education related capital expenditures for Washington was $1,438M. Washington experienced an average annual growth rate of 1.41% from our first education related capital expenditures statistic recorded in 2005. If past trends continue, we forecast the education related capital expenditures to be $1,566 by 2020.

**Comment by ToshMeston** [comment]
Fixed second value.

**Comment by zang0** [comment]
looks good
