### ISSUE TITLE
new map click additions not respecting tab

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#365]
go to:

http://opendatanetwork-staging.herokuapp.com/region/0400000US41/Oregon/earnings/median_male_earnings/2013?

change dropdown to "Median Female earnings"
click on the map for montana

note:

new window is for 'Median Male Earnings (2013)'

NOT

'Median Female Earnings (2013)'

as is selected.

**Comment by ToshMeston** [comment]
I see Median Male Earnings in the popup window.  Are you talking about the white bubble popup?

**Comment by ToshMeston** [comment]
Fixed.  Recreate popup when the model is updated.
