### ISSUE TITLE
data clicks on maps fail in safari

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#371]
go to http://opendatanetwork-staging.herokuapp.com/region/0500000US53033-0500000US53061/King_County_WA-Snohomish_County_WA/classroom_statistics/student_teacher_ratio/2009?

in safari

now click on the map to select a region to compare

note: can't add the region

works fine in chrome

**Comment by ToshMeston** [comment]
This issue happens on prod currently.

**Comment by ToshMeston** [comment]
On Safari it looks like the click is blocked by the .leaflet-tile-container div.  This is really a Safari bug in Leaflet, but I managed a workaround by hiding this div by setting height and width to 0.  I don't really like this fix, but I can see no ill effects on Safari, Chrome or IE.

Fixed.
