### ISSUE TITLE
lives and blds tags not working

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#374]
Looks like we lost the lives and BLDS tags. Data is lost in cetera?

repro:

http://opendatanetwork-staging.herokuapp.com/search?tags=blds
http://opendatanetwork-staging.herokuapp.com/search?tags=lives

note: there used to be > 10 data sets in these results

curiously blds on ODN does have results

http://www.opendatanetwork.com/search?tags=blds

these should be hitting the same end points. @jasonij

**Comment by jasonij** [comment]
Yes, we noticed this some time ago since switching over from Cetera-ETL to Rammstein. Here is the more general ticket: https://socrata.atlassian.net/browse/EN-4594

We actually get an alert once an hour about this, every hour, ongoing.

Supposedly @kavedder figured out what was going on.

**Comment by zang0** [comment]
works on prod. broken in staging. looks both are making the same API call. must be a UI break in staging.

**Comment by jasonij** [comment]
There aren't a lot of results for lives and bldgs though (2 and 37).

**Comment by ToshMeston** [comment]
@zang0 - do I need to do anything here?

**Comment by zang0** [comment]
looks like its working now on staging.
