### ISSUE TITLE
only state forecast clause when data is forecasted

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#380]
http://www.opendatanetwork.com/region/1600000US5363000/Seattle_WA/earnings/median_earnings/2013?

note: forecast statement:

Forecasted data uses a linear extrapolation algorithm which uses only available measured data provided by the U.S. Census American Community Survey. Algorithm details are available HERE.

is present even there is no forecast
![screen shot 2016-04-19 at 12 12 01 pm](https://cloud.githubusercontent.com/assets/1051776/14652180/1009a9c2-0628-11e6-8ef1-11c7837db5dc.png)

**Comment by ToshMeston** [comment]
Fixed.
