### ISSUE TITLE
Add Questions

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#383]
To:

* Get Google linking deeper into the site
* Get Users easier deep access into the site

Create:

_1 a stack ranked list of questions where a question is formulated by a template like:

what is the [variable] for [region]

example:

What is the high school graduation rate for San Jose, CA?

_2 all toggle permutations in our system are covered

_3 include a template of the form:

what is the [variable] for [region1] compared to [region2]

example:

What is the high school graduation rate for San Jose, CA compared to San Francisco, CA?

_4 questions are ranked by population for the covered geographical region. within each region, permutations are ranked such that the defaults appear with a higher value than those requiring user interaction.

_5 100 random questions are included in the homepage chosen such that the probability of selecting a question is roughly equal to (1-(rank in the overall list of questions)/#questions).

_6 all questions are stored in the autosuggest for the search text box and made available as a new autosuggest type

**Comment by aaasen** [comment]
Questions are now available on staging for all non-sparse variables in the following data sources:
 - population
 - earnings
 - education
 - education expenditures
 - GDP
 - cost of living
 - consumption
 - job proximity
 - environmental health
 - health behaviors

Parts 1, 2, 4, and 6 are done. I have not gotten around to generating questions for multiple regions or adding questions to the home page.

For multiple regions, I think that adding another type to autosuggest like "Comparisons" would make the most sense. That way the datasets can be separate and we won't run into issues with deciding whether we should show a single region question versus a comparison question.

For the homepage, I was thinking that we could take a large sample from the autosuggest dataset like this: http://odn.data.socrata.com/views/d6be-a5xs/columns/question/suggest?size=10
and use the population that is encoded in the question to select a good question to display. However, the autosuggestion results don't look very random at all so this won't work.

**Comment by zang0** [comment]
fantastic! very fun to play w/. things noticed:

_7 for a query like: 'gdp seattle' we appropriately suggest questions. but for 'gdp of seattle' we don't. similarly, stuff like: 'cost goods' completes but 'cost of goods' does not. the above stop words stripping in the queries should fix this as i assume you stripped it from the as index. best thing to do here is to strip stop words out of the query and the index - lots of stop words lists out there

_8 looks like we're missing a lot of variable name / region combos. see:

'graduation seattle' completes
'graduation rat' completes
'graduation rate' does not

what algo are you using for the permutation enumeration?

_9 currently stuff like:

business

or

employment

completes to a bunch of zips, and curiously, to a random zip in kansas. have to metro regions w/ greater pop than kansas. looks like the population algo is off

_10 questions that pop up when we just type in a region name look great. i'll file a ticket to get those in the side panel for the regions.

_11 when i type in something like education, the category hit should be above the questions hit. we'll pop the questions inside the landing for the category - i'll file the latter

**Comment by aaasen** [comment]
7. Yes, I stripped stopwords list [here](https://github.com/socrata/opendatanetwork.com/blob/staging/tasks/stopwords.json) from the index and I should do the same for queries. Since there are a lot of stopwords specific to variable names (count, rate, percent, annual, etc.) I made my own list instead of using a general one. I'll probably add the general one to it. 

8. That will be fixed by stripping stopwords from the query. 

9. I pull down some number of autocomplete results then sort by population and display the first 5. These are the first 100 autosuggest results for "construction". For some reason they are all zip codes. I'll look into this.

11. Right now the ordering is regions, questions, datasets, publishers, then categories. Should it be regions, categories, questions, datasets, then publishers?

**Comment by zang0** [comment]
re: 4 - correct

**Comment by aaasen** [comment]
Priority
 - autosuggest to server-side
 - questions on search results #412 
 - questions on side panel
 - rest of #383

**Comment by zang0** [comment]
closing this and replacing w/ more specific ones.
