### ISSUE TITLE
map scroll interferes w/ long scroll in mobile

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#386]
go to: http://opendatanetwork-staging.herokuapp.com/region/1600000US5363000/Seattle_WA/population/population/2013?

on a phone

scroll down

note: the user needs to dance around the map to scroll down to the charts beneath.

solution:

in mobile size, add a expand contract icon in the upper right below the +/- w/ it shrunken by default . once the user taps on the map, changes to an expanded mode mode - finger drags on the map pan the map and all other adds/nav are active, until the user taps on the shrink icon.

**Comment by ToshMeston** [comment]
Implemented on staging.  Please take a look @zang0 and see if that works.

**Comment by zang0** [comment]
Been user testing this. We need to add the 1 tap anywhere on the map (not just on the icon) to expand, but such that the 1 tap doesn't interfere w/ the scroll. Currently folks aren't noticing the expand.

**Comment by ToshMeston** [comment]
Added single tap handler to expand map when collapsed.

**Comment by zang0** [comment]
looks good!
