### ISSUE TITLE
mobile refine control issues

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#387]
Spot checked w/ a few folks - no one seems to notice the Top selected item. Also, not sure why it is even selected, aren't they all selected technically? Lets simplify and have normal drop down behavior, where they all look the same, when the user clicks the down arrow, they make a selection, and the drop down collapses to represent that selected item. when they click go to results, all selected drop downs are respected.

**Comment by ToshMeston** [comment]
Removed 'Go to Results'.  Changed mobile refine menu to use same style for all menu items.  Added code to collapse menus on selection of sub-item.  Added up caret to dismiss the refine menu.

Does that up caret look OK?

**Comment by zang0** [comment]
Caret looks fine. Been playing around, lets do the following:

_1 lets default land to the refine panel being open - problem right now is you search for a city or region, and immediately land on a narrow topic like population - disorienting.

_2 lets not automatically collapse the refine space - only when the user explicitly clicks the up caret.

**Comment by ToshMeston** [comment]
@zang0 - How's this?

**Comment by zang0** [comment]
looks good
