### ISSUE TITLE
mobile view horizontal scroll not enabled per spec on dataset landings

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#389]
goto: http://opendatanetwork-staging.herokuapp.com/dataset/data.montgomerycountymd.gov/icn6-v9z3
in a narrow screen mobile view

note: can't see or get to all columns per this screen shot:

https://www.dropbox.com/s/r64p90msihkxzrq/mobile-ODN-details.psd?dl=0

mobile should just swipe right to see

**Comment by ToshMeston** [comment]
@zang0  This should work.  I can swipe horizontally in the table to reveal more columns on my phone.  On the desktop (with a mac), use two finger scroll.

**Comment by zang0** [comment]
looks good
