### ISSUE TITLE
dataset results refine by not per spec on mobile

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#390]
https://www.dropbox.com/s/ayfoyjvdqyp4urx/mobile-ODN-dataset.psd?dl=0

note: currently, refine by toggles disappear instead of dropping below the text

**Comment by ToshMeston** [comment]
@zang0 - What do you think about replacing these refine dropdowns with a UI that is similar to the mobile refine controls we show on the regions page?  No textbox, red tokens, stacked expandable menu lists.

Like here:
http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/population/population/2013?

**Comment by zang0** [comment]
that works, though lets leave it collapsed by default. dropping pri on this as not important as the rest.

**Comment by ToshMeston** [comment]
Implemented mobile search refine controls on staging.

**Comment by zang0** [comment]
I like it. Can we switch the ordering though, so the refine results stays above the Found 107,120 results statements? A bit awkward to tork controls, then have to look up and down

**Comment by ToshMeston** [comment]
Fixed.
