### ISSUE TITLE
add questions to side panel for regions

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#392]
need to figure out where for mobile and @aaasen can you comment on the API call needed

**Comment by zang0** [comment]
Per today's meeting, API calls for questions discernible from: https://github.com/socrata/opendatanetwork.com/blob/staging/src/data/autosuggest-multi.js#L42

**Comment by zang0** [comment]
desktop geo region landing view:

_1 Note: we'll need to encode the fips codes into the autosuggest dataset so we can get the exact questions for that region

_2 Lets show 5 and tuck the rest under the More so the bot can get into all the questions.

![screen shot 2016-05-05 at 5 32 32 pm](https://cloud.githubusercontent.com/assets/1051776/15061215/6e6cf840-12e7-11e6-83e0-61519837bcf7.png)

Mobile view:

![screen shot 2016-05-05 at 5 39 29 pm](https://cloud.githubusercontent.com/assets/1051776/15061286/5c477be4-12e8-11e6-82ce-3c1a28b5ef9d.png)

**Comment by zang0** [comment]
To @aaasen to add the fips codes into the as index, then to @ToshMeston to put in the front end.

**Comment by zang0** [comment]
to @ToshMeston - FIPs codes are in based on @aaasen's work on #412

**Comment by ToshMeston** [comment]
@zang0 @aaasen  Ah man, we probably need the questions rendered server-side.  Right now it's client.

**Comment by zang0** [comment]
Yeah that's right. How's it going so far?

**Comment by zang0** [comment]
closing this out. we're down to the fallout.
