### ISSUE TITLE
longer menu names stretch mobile view too wide

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#395]
goto: http://opendatanetwork-staging.herokuapp.com/region/310M200US19100-310M200US42660/Dallas_Metro_Area_(TX)-Seattle_Metro_Area_(WA)/cost_of_living/all/2013?

w/ window shrunk down to mobile or on a device, note the "cost of living" menu item pushes the window too wide unnecessarily given the space left in the menu.

<img width="386" alt="screen shot 2016-05-02 at 10 34 59 am" src="https://cloud.githubusercontent.com/assets/1051776/14962002/8e553a7a-1051-11e6-8b12-aaf1e68105a9.png">

**Comment by ToshMeston** [comment]
There was just a long unbroken dataset title farther down the page that was pushing this out - "Dallas_Payments_CHEMTRADE_CHEMICAL".  Fixed.
