### ISSUE TITLE
maintain refine results state

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#399]
if user closes refine by in mobile mode, keep it closed unless they open it

ex: goto: http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/education/high_school_graduation_rate/2013?

and collapse the refine results 

now, click on  a region in the map and click go to

note: the refine results section expands - should maintain state here and until the user clicks the button again OR does another region search from the main bar (since the controls get reset to another state, the user should know)

**Comment by ToshMeston** [comment]
Fixed.
