### ISSUE TITLE
make hierarchy more obvious in mobile refine filters

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#402]
On blind tests w/ users, noticing they aren't grocking the filter hierarchy. Can we try to indent the filters, something like:

Demographics
- Population
-- Population count
--- 2013
![screen shot 2016-05-04 at 11 50 29 am](https://cloud.githubusercontent.com/assets/1051776/15025511/6982c3b8-11ee-11e6-81d4-da5663b364c3.png)

**Comment by ToshMeston** [comment]
@zang0 what do you think of something like this?

http://opendatanetwork-staging.herokuapp.com/region/310M200US19100/Dallas_Metro_Area_(TX)/gdp/annual_change_in_gdp/2013?

**Comment by zang0** [comment]
Kind of works. What happens when you indent each one down a bit more? If it looks freaky, I can live w/ this.

**Comment by ToshMeston** [comment]
Indenting any more puts pressure on long menu item strings like "Population Rate of Change" on narrow devices.  This what it looks like on a iPhone 5S.

![simulator screen shot may 11 2016 3 55 08 pm](https://cloud.githubusercontent.com/assets/987532/15199129/c03b5ec0-1790-11e6-98ec-16e1271d9bd8.png)

**Comment by zang0** [comment]
looks good. lets stick w/ this.
