### ISSUE TITLE
extra ghost bars in dataset landing

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#404]
http://opendatanetwork-staging.herokuapp.com/dataset/data.murphytx.org/ks6s-d2hj?

see attached image - note the ghost horizontal and vertical bar
![screen shot 2016-05-04 at 12 08 51 pm](https://cloud.githubusercontent.com/assets/1051776/15026025/0fca6e2c-11f1-11e6-9781-59a1f7020489.png)

**Comment by ToshMeston** [comment]
@zang0  Hm, I don't have that.  Is it an extension doing that?

**Comment by zang0** [comment]
huh, me neither now. maybe it was a crusty cache issue.
