### ISSUE TITLE
add questions on matching search results

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#412]
when the user hits enter and searches on something w/ matching questions, lets hit an in document search dataset to generate something like the attached plot. To @aaasen to generate the dataset on autosuggest generation - note: won't need all the keyword permutation stuff due to the inverted index by word.

![screen shot 2016-05-05 at 6 08 54 pm](https://cloud.githubusercontent.com/assets/1051776/15061651/9fb37e74-12ec-11e6-9051-8c7ca775cead.png)

**Comment by aaasen** [comment]
Done. See http://opendatanetwork-staging.herokuapp.com/search?q=seattle as an example. Questions are generated client-side since I don't think that we need the bot on search pages like this and it makes the code much simpler since we can reuse the autosuggest code.

**Comment by zang0** [comment]
We actually do want the bot on these pages, but especially so on #392 as we need to increase page rank on the deep question driven links. re #392, we're going to be linking in from customer catalog pages directly into geo region. Other issues:

_1 blue text of ?s should be black - we have lots of black links

_2 lets show a max of 2 questions w/ a More link in the lower right

_3 change the ? to the icon used on the autosuggest

_4 missing lots of matches:

_4.1 'seattle gdp' matches ?s but not 'seattle cost of living' or 'seattle graduation rate'

what index is being used? where's the dataset?

_4.2 king matches to kingston - what stemming is being applied?
