### ISSUE TITLE
ODN sanitize advanced catalog query strings

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#416]
see: https://socrata.atlassian.net/browse/EN-6111

**Comment by aaasen** [comment]
Fixed by replacing all non-alphanumeric characters in region names with spaces. In production.

**Comment by zang0** [comment]
Seeing below on adding kansas city mo to: http://www.opendatanetwork.com/region/1600000US4752006/Nashville-Davidson_TN/population/population/2013?

https://federal.demo.socrata.com/resource/bdeb-mf9k.json?id=1600000US2938000 500 (Server Error)k.cors.a.crossDomain.send @ jquery.min.js:4n.extend.ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4n.extend.getJSON @ jquery.min.js:4_createClass.value @ region-lookup.js:4(anonymous function) @ region-lookup.js:27_createClass.value @ region-lookup.js:26_createClass.value @ region-lookup.js:42(anonymous function) @ search-page-controller.js:105(anonymous function) @ autosuggest-source.js:138(anonymous function) @ d3.min.js:1
region-lookup.js:32 Uncaught [object Object](anonymous function) @ region-lookup.js:32(anonymous function) @ jquery.min.js:2j @ jquery.min.js:2k.fireWith @ jquery.min.js:2x @ jquery.min.js:4(anonymous function) @ jquery.min.js:4
jquery.min.js:4 GET https://federal.demo.socrata.com/resource/bdeb-mf9k.json?id=1600000US2938000 500 (Server Error)k.cors.a.crossDomain.send @ jquery.min.js:4n.extend.ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4n.extend.getJSON @ jquery.min.js:4_createClass.value @ region-lookup.js:4(anonymous function) @ region-lookup.js:27_createClass.value @ region-lookup.js:26_createClass.value @ region-lookup.js:42(anonymous function) @ search-page-controller.js:105(anonymous function) @ autosuggest-source.js:138(anonymous function) @ d3.min.js:1
region-lookup.js:32 Uncaught [object Object](anonymous function) @ region-lookup.js:32(anonymous function) @ jquery.min.js:2j @ jquery.min.js:2k.fireWith @ jquery.min.js:2x @ jquery.min.js:4(anonymous function) @ jquery.min.js:4
jquery.min.js:4 GET https://federal.demo.socrata.com/resource/bdeb-mf9k.json?id=1600000US2938000 500 (Server Error)k.cors.a.crossDomain.send @ jquery.min.js:4n.extend.ajax @ jquery.min.js:4n.(anonymous function) @ jquery.min.js:4n.extend.getJSON @ jquery.min.js:4_createClass.value @ region-lookup.js:4(anonymous function) @ region-lookup.js:27_createClass.value @ region-lookup.js:26_createClass.value @ region-lookup.js:42(anonymous function) @ search-page-controller.js:105(anonymous function) @ autosuggest-source.js:138(anonymous function) @ d3.min.js:1
region-lookup.js:32 Uncaught [object Object]

**Comment by aaasen** [comment]
Do you mean this URL? http://www.opendatanetwork.com/region/1600000US4752006-1600000US2938000/Nashville-Davidson_TN-Kansas_City_MO/population/population/2013?

I'm not getting an error there.

**Comment by zang0** [comment]
yeah, looks ok, not sure - closing.
