### ISSUE TITLE
investigate what slowed down queries by ~2x post mobile launch

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#417]
![screen shot 2016-05-19 at 9 28 40 am](https://cloud.githubusercontent.com/assets/1051776/15401378/26e6db7c-1da4-11e6-83e1-ab3cea1ff659.png)

**Comment by aaasen** [comment]
I think that this is my fault. Accidentally disabled the cache at some point. Sorry! Fixed and will deploy soon.
