### ISSUE TITLE
add questions to filter constraints in mobile view

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#422]
See attached image. Currently the questions drop out on mobile.
![screen shot 2016-05-20 at 10 37 20 am](https://cloud.githubusercontent.com/assets/1051776/15436475/f5b8ab56-1e76-11e6-82e8-a03fee8712be.png)

**Comment by zang0** [comment]
to @aaasen to specify requisite api calls, then to @ToshMeston for impl

**Comment by ToshMeston** [comment]
Implemented.  I didn't add the question icon as the horizontal space is limited and it looked strange with the question not lining up vertically with the other text strings.
