### ISSUE TITLE
move map in mobile view below line charts

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#423]
folks in mobile seem confused by the map complexity. want to experiment and try to place them below all the line charts to see if our engagement #s go up

**Comment by ToshMeston** [comment]
Currently there is only one map element for desktop and mobile.  To move this for mobile only, we will need to copy the HTML of the map and map summary.  Let's do later when we can test it more.

**Comment by ToshMeston** [comment]
Fixed.
