### ISSUE TITLE
questions tweaks

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#424]
_1 drop # displayed questions to 15 in search results, e.g.

http://opendatanetwork-staging.herokuapp.com/search?q=seattle

_2 and in side bar on more click here

http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/population/population/2013?

_3 change 

"SHOW MORE QUESTIONS" to "SHOW MORE" and
"SHOW FEWER QUESTIONS" to "SHOW FEWER"

in side bar and search results.

**Comment by ToshMeston** [comment]
Fixed.
