### ISSUE TITLE
need questions from all comparisons on comp pages

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#426]
need to add questions like: what is the gdp of portland vs seattle. results should handle the following scenarios:

_1 comparison pages like http://opendatanetwork-staging.herokuapp.com/region/310M200US42660-310M200US19740/Seattle_Metro_Area_(WA)-Denver_Metro_Area_(CO)/cost_of_living/all/2013?
should have all listed questions for both regions, e.g. What is the GDP per capita of Seattle vs Portland?

_2 searches and autosuggests like 'seattle portland gdp' should resolve to the comparison questions

**Comment by aaasen** [comment]
Part 1 is finished. Punting on part 2.
