### ISSUE TITLE
disable questions on comp pages until #426 is done

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#427]
Until #426 is implemented, we should disable all questions on comparison pages. Currently they are confusing, this means they should not appear in pages like: 

http://opendatanetwork-staging.herokuapp.com/region/310M200US38900-310M200US28140/Portland_Metro_Area_(OR-WA)-Kansas_City_Metro_Area_(MO-KS)/occupations/computers_and_math/2013?

in either the wide screen or mobile views.

**Comment by ToshMeston** [comment]
All I did to disable these was remove the includes of the three partial templates.  Check the diff to restore them.  Fixed.

**Comment by zang0** [comment]
note: we only want them gone on the comparison pages, x vs y, not just x pages. i filed another ticket

**Comment by ToshMeston** [comment]
Fixed.  Removed questions for >=2 regions.
