### ISSUE TITLE
mobile view nav tweaks don't change the displayed question

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#428]
go to: http://opendatanetwork-staging.herokuapp.com/region/1600000US5363000/Seattle_WA/population/population/2013?

note the question: What is the population count of Seattle, WA?

now change the "population Count" drop down to "Population Rate of Change" - Note: the question did not change.

looks like the first 2 drop downs behave as expected, the lower 2 fail.

**Comment by ToshMeston** [comment]
Fixed.

**Comment by zang0** [comment]
Re-opening. Can't verify until #435 is addressed.

**Comment by ToshMeston** [comment]
You can see this changing now.
