### ISSUE TITLE
change default min map height in mobile

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#429]
in mobile, go to: http://opendatanetwork-staging.herokuapp.com/region/1600000US2407125/Bethesda_MD/city_crime/theft_rate/2016?

note the super squished map (also attached) and how it becomes incoherant

now expand, note: generally legible.

todo: change default collapsed view to EITHER drop the legend, OR expand it a bit more so doesn't look so off

**Comment by ToshMeston** [comment]
Increased the collapsed height by 50%.  Looks better.

**Comment by zang0** [comment]
default works, but when you collapse it using the icon, it goes back to the old squished size

**Comment by ToshMeston** [comment]
Should have caught this.  Fixed.
