### ISSUE TITLE
add questions to the home page

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#432]
Envisioning 1000 questions that are google bot visible, but they're just cycling through one after the other just below the search box in an animation like:

http://codecanyon.net/item/textfx-a-jquery-text-animation-tool/full_screen_preview/309565

where the user can click on any one and they'll resolve to the URL

**Comment by zang0** [comment]
5 100 random questions are included in the homepage chosen such that the probability of selecting a question is roughly equal to (1-(rank in the overall list of questions)/#questions).

**Comment by zang0** [comment]
UI - lets just show the top 10 questions just under the search box, with the rest tucked underneath a more. To @ToshMeston  to implement

**Comment by ToshMeston** [comment]
OK, right now on staging, we are taking the most populated MSA, county and city from each state (which we already have for the geographical regions section).  From those ~150 regions, we randomly choose 100 regions.  For each of the 100 regions, we get the list questions list via the auto-complete API.  We choose 1 random question for each region, and then we render those questions on the home page.

The 100 auto-complete promises, to get the questions are executed in parallel, and some of those promises make web requests to determine what questions exist.  The request responses are cached.  If the request misses cache, it takes about 500-1000ms.  If there is a cache hit, it takes about 70-300ms.

Let me know if the UI is what you had in mind.  10 questions under the text box in the red hero area gets pretty crammed and overflows oddly when "Show More" is clicked.  For this reason, I just made a separate section.  Happy to alter it as needed.

**Comment by zang0** [comment]
questions themselves look good! some feedback:

_1 looks a bit funky in mobile - maybe drop # of questions and font size
_2 add a ~"less results" to shrink back up the expansion
_3 be consistent w/ terminology on expansion/contraction, e.g. regions says "Show More Regions" but questions says "Show More"

**Comment by ToshMeston** [comment]
OK this is a bit better.  Made the Questions section into an expandable thing like "Data Categories" on mobile.
