### ISSUE TITLE
URLs w/ year are broken

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#433]
Looks like somehow we broke URLs ending in a year. We need to get a fix out asap as we're releasing a marketing letter that has a bunch of these URLs in them.

examples:

_1
http://www.opendatanetwork.com/region/0500000US53033/King_County_WA/population/population/2010?

note: should resolve to 2010, but resolves to 2013

_2
http://www.opendatanetwork.com/region/0500000US25017-0500000US50011-0500000US53061/Middlesex_County_MA-Franklin_County_VT-Snohomish_County_WA/classroom_statistics/student_teacher_ratio/2013

note: should resolve to 2013 but resolves to 2014

**Comment by ToshMeston** [comment]
Fixed and deployed to prod since it was the only commit.
