### ISSUE TITLE
quicklinks surfacing dead links

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#434]
![screen shot 2016-05-25 at 11 54 51 am](https://cloud.githubusercontent.com/assets/1051776/15552499/8758d210-226f-11e6-86f3-e7f2aafb38a1.png)

**Comment by zang0** [comment]
mark https://socrata.atlassian.net/browse/EN-6202 done when fixed

**Comment by ToshMeston** [comment]
@zang0  These dead links are coming back from cetera.  They should remove from their index.

**Comment by zang0** [comment]
don't include any count=0 results

**Comment by ToshMeston** [comment]
Removed publishers without datasets in the app logic.  I have a email out to cetera people to see if this is possible with the rest API.  If it is, I'll change the code to pass the appropriate params.

Fixed.
