### ISSUE TITLE
questions in mobile disappeared from region landings

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#435]
missing from search landings as well: http://opendatanetwork-staging.herokuapp.com/search?q=gdp

see live site vs staging mobile:
![screen shot 2016-05-26 at 9 42 38 am](https://cloud.githubusercontent.com/assets/1051776/15582493/2cab3fe4-2326-11e6-9c4c-8e489f0f79b5.png)
![screen shot 2016-05-26 at 9 42 28 am](https://cloud.githubusercontent.com/assets/1051776/15582492/2ca89492-2326-11e6-90f0-5e61df5fbd27.png)

**Comment by ToshMeston** [comment]
Restored questions generally.  Will disable for >= 2 regions shortly.
