### ISSUE TITLE
places map description not remaining below map on mobile view

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#436]
![screen shot 2016-05-26 at 9 49 04 am](https://cloud.githubusercontent.com/assets/1051776/15582701/2e340980-2327-11e6-99ad-7b2a59ba2dfa.png)

**Comment by ToshMeston** [comment]
http://opendatanetwork-staging.herokuapp.com/region/1600000US5363000/Seattle_WA/education_places/head_start_center?

Fixed.
