### ISSUE TITLE
animated homepage search box

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#437]
cycle thorugh the hp questions + some categories, datasets, etc

**Comment by ToshMeston** [comment]
The set of sample entries is in src/home-page-controller.js.  We can add/remove as needed.
Fixed.

**Comment by zang0** [comment]
Few comments:

* Can we strip the words "What is the" about half the time on the questions?
* Change the ratio so the questions don't dominate quite as strongly, right now, because they are longer, it takes longer for their questions to complete
* Can we just add the variable name on occassion, e.g. adult obesity rate
* Can we just add the variabel name + the location name on occassion, e.g. seattle gdp

**Comment by ToshMeston** [comment]
OK, I switched this up.  I took a new set of random questions and combined it with some dataset titles, categories and regions.  It breaks down like this - 40 samples.

1/4 - What is... ?
1/4 - variable name
1/4 - variable name + location
1/4 - datasets, categories, cities
