### ISSUE TITLE
https links appearing on google w/ cert problem

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#439]
search on google: excessive drinking rate tennessee

note google link to odn is https - click on it, note cert problem
![screen shot 2016-05-27 at 3 37 05 pm](https://cloud.githubusercontent.com/assets/1051776/15622751/fc937708-2420-11e6-983e-44449394ad67.png)
![screen shot 2016-05-27 at 3 35 56 pm](https://cloud.githubusercontent.com/assets/1051776/15622752/fc940a92-2420-11e6-8b9d-9b40ce7af929.png)

**Comment by ToshMeston** [comment]
@chrismetcalf  Hey Chris, there is an issue with the SSL cert.  Did you set the cert up?
https://www.opendatanetwork.com/

**Comment by chrismetcalf** [comment]
@ToshMeston We don't have an SSL cert, we punted on it. https://github.com/socrata/opendatanetwork.com/issues/212

**Comment by ToshMeston** [comment]
Added code such that if we get an HTTPS request, the app returns a 301 (permanent redirect) to the browser for the same URL under HTTP, this will let the Googlebot know we prefer HTTP and to update the index.

Not sure how an HTTPS url got out in the wild.  The sitemap contains only HTTP.

**Comment by ToshMeston** [comment]
So we are trying to think what to do here when an HTTPS request comes in.  I added code to redirect HTTPS to HTTP, but we're not sure if a spider will see a cert failure if it tries to hit an HTTPS URL or will it get the redirect header first?  I think @zang0 wants to leave the redirect code and set up a cert.  @chrismetcalf you want set that up?  Maybe we should talk about this one on Thursday.

**Comment by chrismetcalf** [comment]
It's pretty easy to set up an SSL cert, it just takes a little while since I need to work through our ops team. I'll file a ticket to see if we can get that started.

**Comment by chrismetcalf** [comment]
For those with JIRA access: https://socrata.atlassian.net/browse/EN-6650

**Comment by chrismetcalf** [comment]
Looks like my ticket with the ops team to get an SSL cert created is stalled. I've bumped it and hopefully we'll get some indication on how we can get that prioritized properly.

**Comment by chrismetcalf** [comment]
Issue is now assigned to a group, but no indication as to when it'll actually get to it. I've bumped the severity to `Major` and pinged them again to see if it can get some attention.

If I don't see something soon, maybe we should just go with Let's Encrypt or something. Its at least a start.

**Comment by chrismetcalf** [comment]
@jhaynes got back to me and he's going to be issuing some certs tomorrow morning, and plans to include ours as well

**Comment by chrismetcalf** [comment]
Cert is generated, and @jhaynes is going to take a whack at pushing the keys to Heroku this afternoon!

**Comment by chrismetcalf** [comment]
Pushed a change to staging that will automatically redirect users to the HTTPS version.

@aaasen Is there a safe place to change the API calls so that they can all go to the https://*.herokuapp.com version in staging, and https://api.opendatanetwork.com in production?

**Comment by aaasen** [comment]
@chrismetcalf Do you mean https://odn-backend.herokuapp.com/ in staging? Why wouldn't we just use https://api.opendatanetwork.com all the time?
