### ISSUE TITLE
500's on region pages causing Pingdom outages

### ISSUE THREAD

**Issue by chrismetcalf** [socrata/opendatanetwork.com#440]
This morning we had a spate of 500 errors that ended up triggering an alert to the engineering oncall. Looking at the logs (query: `_source=opendatanetwork.com "HTTP/1.1\" 500"`) they were region pages. Example:

    245 <190>1 2016-05-31T17:12:28.908355+00:00 host app web.2 - ::ffff:10.149.120.148 - - [31/May/2016:17:12:28 +0000] "GET /region/8600000US54644/54644_ZIP_Code HTTP/1.1" 500 1008 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
    211 <190>1 2016-05-31T16:48:33.276768+00:00 host app web.1 - ::ffff:10.203.216.91 - - [31/May/2016:16:48:33 +0000] "GET /search?q=bikes HTTP/1.1" 500 1008 "-" "Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)"

**Comment by zang0** [comment]
Chris what are the pingdom rules we are using to alert on?

**Comment by aaasen** [comment]
Looks like the backend returned some 500s at around 3:38 AM which caused us to return 500s. Not much we can do if the backend is down.

**Comment by chrismetcalf** [comment]
@zang0 It looks like we only have the following check set up in Pingdom:

    http://www.opendatanetwork.com/search?q=bikes
