### ISSUE TITLE
Design/Implement/Deploy ODN API /related endpoint

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#444]
full pass for /related endpoint

_1. design API - current @ http://docs.odn.apiary.io/#reference/0/relatives
_2. impl
_3. implement tests on all REST calls
_4. write javascript wrapper
_5. implement tests on js lib
_6. deploy service
_7. write monitor for api service
_8. replace all prior calls in odn project w/ network calls to api.opendatanetwork.com
_9. add api icon w/ tooltip and link to the API endpoint in ODN app
_10. deploy to staging

**Comment by aaasen** [comment]
Parts 1-7 are complete. 4 and 5 were not necessary for this endpoint. Assigning to @ToshMeston to integrate into the front end.

See detail here: https://github.com/socrata/odn-backend

**Comment by zang0** [comment]
Details on Site API exposure

<img width="754" alt="screen shot 2016-06-27 at 11 43 54 am" src="https://cloud.githubusercontent.com/assets/1051776/16391468/23f273e6-3c5c-11e6-8ef6-e5324fcc9dfb.png">

**Comment by ToshMeston** [comment]
I switched Relatives.js to use the /related endpoint for the side navigation on the region page - 17b8003.

For the regions on the home page, I have left it as is, because we pre-generated a JSON file of all the MSAs, counties, cities for the 50 states and we are just looping over that.  There is no API to replace and I didn't want to introduce 50 API call to get that data.

Still need to do _9.

**Comment by zang0** [comment]
Does it make sense to change the pre-generation scripts to use the new calls?

**Comment by aaasen** [comment]
I don't think that it makes sense right row, but it might once we have a `/entity` endpoint.

**Comment by ToshMeston** [comment]
What do you guys think of the the API links and boxes?

http://opendatanetwork-staging.herokuapp.com/region/310M200US31080/Los_Angeles_Metro_Area_(CA)/population/population/2013?

**Comment by zang0** [comment]
Love it!!! Some things I noticed:

_1 We should check if there are results before showing the API icon. Example: zip codes don't have peers: http://opendatanetwork-staging.herokuapp.com/region/8600000US98117/98117_ZIP_Code

_2 Most of the /relatives calls have limit=10 but we only show 5, should set to 5.

**Comment by ToshMeston** [comment]
Implemented.
