### ISSUE TITLE
+ fbi crime data nationwide

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#445]
take 1:

* multiyear
* cities only

**Comment by chrismetcalf** [comment]
@aaasen Can you lend me a hand getting the last bit wired in?

I've got a WIP commit pushed to a branch: https://github.com/socrata/opendatanetwork.com/tree/chrismetcalf/ucr-crimes

I've been banging my head on it but there are a couple of things I can't figure out:

1. With the new format I can't figure out how to get the one chart displaying "rate" while the other displays "count"
2. It looks like I got the scale to work on the map, but the flyout still claims there's no data

I can bang at it more but I figure you'll be able to find my error pretty quickly.

Thanks! 🍺

**Comment by zang0** [comment]
closing this, rest looks covered by #453
