### ISSUE TITLE
Design/Implement/Deploy/Adapt UI to ODN API /data endpoints

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#446]
_1 design and review API /data calls, specifically: 

http://docs.odn.apiary.io/#reference/0/data-availability/find-the-relatives-of-an-entity

and

http://docs.odn.apiary.io/#reference/0/data-constraints/get-constraint-permutations-for-entities

_2 implement backend

_3 implement API tests

_4 add to monitor

_5 replace API calls in opendatanetwork.com

_6 add UI links w/ mouseovers

<img width="776" alt="screen shot 2016-06-28 at 5 40 01 pm" src="https://cloud.githubusercontent.com/assets/1051776/16436931/1a0ba978-3d57-11e6-8c20-43119c00189d.png">
<img width="772" alt="screen shot 2016-06-28 at 5 39 54 pm" src="https://cloud.githubusercontent.com/assets/1051776/16436932/1a0c194e-3d57-11e6-8ba6-29f671212808.png">
<img width="781" alt="screen shot 2016-06-28 at 5 39 48 pm" src="https://cloud.githubusercontent.com/assets/1051776/16436933/1a0eb41a-3d57-11e6-86cb-1a5dd0eb28fb.png">

**Comment by aaasen** [comment]
Parts 1-4 are done. All datasets except for `city_crime` are now exposed via the ODN API. The city crime dataset was excluded since we are abandoning it in favor of the nationwide FBI data. I had to modify the BRFSS dataset quite a bit to get it into the new schema, but I think it will work.

Giving this to Tosh to integrate into the UI.

**Comment by ToshMeston** [comment]
The topics (tabs) and datasets (first dropdown) are populating from the data availability response.  The variables (second dropdown) and constraints (third "year" dropdown) are starting to get deep into the code of Lane (variable control MAP_SOURCES, etc).  @aaasen you want to take this?

**Comment by zang0** [comment]
@ToshMeston We're trying to keep the pedal to the metal on getting through the full API impl done. Can you take a crack at it and pull in Lane as you get stuck? Really like to have more knowledge on the code base anyway.

**Comment by ToshMeston** [comment]
Need API buttons next to the chart titles.  Otherwise, this one I think is done.

**Comment by ToshMeston** [comment]
1-4 implemented by Lane.
5-6 now done.

@zang0 - I feel like the API info box next to the chart titles should be for the data/values API not /availability.  Is availability what you intended?  Let me know and we can change.
