### ISSUE TITLE
Add app_token for requests coming in from odn.com and apiary

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#447]
Lets sign up for an app token and use it in http requests for 

_1 all odn.com requests and 
_2 apiary requests 

so we can track these separately. To @chrismetcalf to do _2, then to @ToshMeston to impl _1.

**Comment by chrismetcalf** [comment]
Apiary changes pushed to socrata/odn-backen:

- https://github.com/socrata/odn-backend/commit/37546ab13fac3d8cc076c920be43cb7142a5743e
- https://github.com/socrata/odn-backend/commit/0efe18b15ccaad2fb4ea8edce803d40bf475fd85

**Comment by chrismetcalf** [comment]
It looks like @ToshMeston had already added the app tokens to the UI, but I went through and made them consistent with the Apiary docs. I think this one can be closed.
