### ISSUE TITLE
drop case in api commentary for endpoints

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#448]
in all yellow mouseovers, can we change:

/RELATED/PEER ENDPOINT

to 

/related/peer endpoint

it uses much less width, looks nicer, and hopefully doesn't wrap

**Comment by ToshMeston** [comment]
Fixed.

**Comment by ToshMeston** [comment]
OK, I changed this to "Endpoint" because lowercase "endpoint looks strange as header text.
