### ISSUE TITLE
design/implement/test/adapt UX for /charts and /maps

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#449]
/charts and /maps roughly defined @ https://docs.google.com/document/d/1GpBdkDgufpXH4TJpWypmuYYVZyVaWqtzs98uYuyNEZI

**Comment by aaasen** [comment]
The `/data/v1/values/` endpoint is ready. Descriptions could use some improvement.

**Comment by aaasen** [comment]
For example, to get the population over time of the United States and Washington with descriptions and three years of forecasted data: 

http://odn-backend.herokuapp.com/data/v1/values?variable=demographics.population.count&entity_id=0100000US,0400000US53&forecast=3&describe=true

```
{
    "data": [
        [
            "year",
            "0100000US",
            "0400000US53",
            "forecast"
        ],
        [
            2009,
            301461533,
            6465755,
            false
        ],
        [
            2010,
            303965272,
            6561297,
            false
        ],
        [
            2011,
            306603772,
            6652845,
            false
        ],
        [
            2012,
            309138711,
            6738714,
            false
        ],
        [
            2013,
            311536594,
            6819579,
            false
        ],
        [
            2014,
            314055359.25,
            6908035,
            true
        ],
        [
            2015,
            316574124.5,
            6996491,
            true
        ],
        [
            2016,
            319092889.75,
            7084947,
            true
        ]
    ],
    "forecast_info": {
        "algorithm_name": "linear",
        "algorithm_url": "https://en.wikipedia.org/wiki/Extrapolation#Linear_extrapolation"
    },
    "description": "The population of United States was 301,461,533 for the year of 2009. The population of Washington was 6,465,755 for the year of 2009. The population of United States was 303,965,272 for the year of 2010. The population of Washington was 6,561,297 for the year of 2010. The population of United States was 306,603,772 for the year of 2011. The population of Washington was 6,652,845 for the year of 2011. The population of United States was 309,138,711 for the year of 2012. The population of Washington was 6,738,714 for the year of 2012. The population of United States was 311,536,594 for the year of 2013. The population of Washington was 6,819,579 for the year of 2013."
}
```

This is the sort of query that we would use to populate the line chart.

**Comment by zang0** [comment]
Fantastic. To Tosh to begin wiring in the front end.

**Comment by aaasen** [comment]
I expanded the documentation for this endpoint in Apiary. Let me know if you have any questions.

**Comment by aaasen** [comment]
I completed a first pass at the maps endpoint. Demo here: http://jsfiddle.net/w4nxL46m/38/

Main features are incremental loading and fetching different levels of detail based on zoom level. Try zooming in on Seattle and watch the boundaries sharpen.

Tomorrow I am going to work on adding places and zip codes so we can finally map them.

**Comment by zang0** [comment]
Totally awesome!!! @chrismetcalf Check this out!

**Comment by aaasen** [comment]
Mapping is now available for places and ZIP codes:
 - Seattle: http://jsfiddle.net/w4nxL46m/44/
 - 98122 ZIP Code: http://jsfiddle.net/w4nxL46m/45/

There are about 30,000 places and ZIPs in the US, so instead of sending them all I'm just sending the 1,000 largest by land area. The selected regions are always shown regardless of their size. This works very well for places, but not quite as well for ZIPs since they tend to be large in the midwest and small in the east. I'm thinking that the UI will give some warning to zoom in to see all regions when not all are shown. 

I've also implemented map sessions using memcache so this should scale well. I'll monitor the load and bump up our capacity if necessary.

**Comment by aaasen** [comment]
One weird issue. NYC shows up in the data here: https://odn.data.socrata.com/dataset/ODN-Geodata-Places-V2/funa-vn5h but not here: https://odn.data.socrata.com/resource/rmqq-dzu4.json?id=1600000US3651000

Not really sure why, but it seems to be a Socrata issue.

**Comment by zang0** [comment]
closing this. opening fine grained tickets.
