### ISSUE TITLE
Design/Implement/Deploy/Adapt UI to ODN API /suggest endpoints

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#450]

**Comment by zang0** [comment]
Back end looks done. To Tosh for front end re-wiring. @aaasen Please comment if there are any remaining testing or other issues.

**Comment by aaasen** [comment]
Yeah it's done. At some point I will cycle back and polish up the questions but we at least have parity with the current frontend.

**Comment by zang0** [comment]
elevating pri so we can get the last of the features out of the way.

**Comment by ToshMeston** [comment]
OK.  This is adapted and deployed to staging.  Fixed.
