### ISSUE TITLE
Design/Implement/Deploy/Adapt UI to ODN API /search endpoints

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#451]

**Comment by aaasen** [comment]
API is done, assigning to Tosh.

**Comment by ToshMeston** [comment]
@aaasen Is this wrapping cetera catalog API?

**Comment by aaasen** [comment]
`/search/v1/dataset` is for getting datasets on a region page and `/search/v1/question` is for getting questions on the search results page. We decided to not directly wrap cetera for simple requests.

**Comment by ToshMeston** [comment]
Changed the regions page to issue a search dataset request.  The simple search results page still queries cetera.  Fixed.
