### ISSUE TITLE
front end needs to change to latest API

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#454]
_1 see: http://odn-backend.herokuapp.com/related/v1/peer?id=1600000US5363000&limit=5

note error. latest is entity_id not id - walk through all the front end calls and make sure they work. also note: 

Appears on: Example:
Peers of Seattle, WA

for: http://opendatanetwork-staging.herokuapp.com/region/1600000US5363000/Seattle_WA/population/population/2013?

_2 how is the UI itself working? Is it not using the same API call?

**Comment by ToshMeston** [comment]
Oops.  Updated the relatives.js and data.js, just not the links in the API infoboxes.

Fixed.
