### ISSUE TITLE
api badge for odn search + cetera search

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#457]
Add badge w/ onclick to yellow box in search row to far right for all queries w/ pointers to cetera docs. Should say:

/catalog/v1

Example: 
Search for Puyallup

Docs: Full text search (or "Search particular domains" or "Search particular categories" depending on filter toggles)

link to: http://docs.cetera.apiary.io/

**Comment by zang0** [comment]
![screen shot 2016-07-18 at 2 42 33 pm](https://cloud.githubusercontent.com/assets/1051776/16931447/e860489e-4cf5-11e6-927c-14f12474f37a.png)

**Comment by ToshMeston** [comment]
Fixed in iss449 branch.

**Comment by ToshMeston** [comment]
@zang0 Is this right to be pointing at the cetera catalog API.  Probably should be http://docs.odn.apiary.io/#reference/0/search-datasets/get-datasets, correct?  Please reactivate and assign it to me if so.  Thx.
