### ISSUE TITLE
change api prod to api.opendatanetwork.com

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#460]
from: http://odn-backend.herokuapp.com/
to: http://api.opendatanetwork.com/

@chrismetcalf Can you do this or tell us who can?

**Comment by chrismetcalf** [comment]
Filed the appropriate internal ticket for this: https://socrata.atlassian.net/browse/EN-8325

**Comment by chrismetcalf** [comment]
Added the domain config to Heroku. As soon as DevOps adds the CNAME, we should be good to go.

**Comment by chrismetcalf** [comment]
CNAME is in.

@aaasen Can you update the frontend to call via the new domain CNAME?
