### ISSUE TITLE
Add Questions API Badge to Site

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#461]
Alongside QUESTIONS, need badge w/ yellow onclick expansion box that says:

/search/v1/question Endpoint

Example: questions for Seattle, WA

API Docs: 
Get search results (links to: http://docs.odn.apiary.io/#reference/0/search/get-search-results)

Implement once https://github.com/socrata/odn-backend/issues/15 is done

**Comment by ToshMeston** [comment]
Added to the Questions in the side-bar and in the search results.  Fixed.
