### ISSUE TITLE
Add Suggest API badge

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#462]
Add autosuggest badge in the drop down window @ the bottom. Should be selectable like other entries. Should only show if there's a match. Docs example should use what's in the text box right now.

![screen shot 2016-07-18 at 2 35 46 pm](https://cloud.githubusercontent.com/assets/1051776/16931280/fb65a728-4cf4-11e6-891e-b23eb6452df0.png)

**Comment by ToshMeston** [comment]
Is there a better place for the green API button?  This gutter isn't always empty.  For instance, search for "nasa".

**Comment by zang0** [comment]
peer meeting, add full width line underneath the last entry, then add api

**Comment by ToshMeston** [comment]
Implemented with green text.  Let me know if we should tweak anything.  Fixed.

**Comment by zang0** [comment]
Looks good for now. Thanks!
