### ISSUE TITLE
autosuggest for crime data

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#463]

**Comment by chrismetcalf** [comment]
Getting an OOM error regenerating the autosuggestion questions:

![2016-08-17 at 1 06 pm](https://cloud.githubusercontent.com/assets/19971/17751321/7f64fa7c-647b-11e6-9169-91f015b45243.png)

@zang0, @ToshMeston Do either of you remember if this is the right way of regenerating that data file?

**Comment by zang0** [comment]
per meeting - override node heap setting

**Comment by chrismetcalf** [comment]
`--max_old_space_size (max size of the old space (in Mbytes))`

**Comment by chrismetcalf** [comment]
@aaasen Got the new questions.csv file to generate and I'm uploading a new dataset now. That's the correct procedure, right?

**Comment by aaasen** [comment]
Yeah. Upload it and then use bootstrap the datalens to update autosuggest.

**Comment by chrismetcalf** [comment]
Alright, new API with crime questions: https://dev.socrata.com/foundry/odn.data.socrata.com/gav2-me5f

**Comment by chrismetcalf** [comment]
@aaasen Looks like I just need to replace the autocomplete fxf in https://github.com/socrata/odn-backend/blob/3b7d92ca98b5575942f56839d3e7ad5a25c1d891/data/autosuggest-sources.js#L26, correct?

@ToshMeston Based on #475, it looks like we should be using the new questions API from that dataset, right?

**Comment by aaasen** [comment]
Yes that's correct.

**Comment by chrismetcalf** [comment]
https://github.com/socrata/odn-backend/pull/39
