### ISSUE TITLE
Ensure user-agent is set for catalog API requests

### ISSUE THREAD

**Issue by rlvoyer** [socrata/opendatanetwork.com#466]
Requests from the ODN make up a large percentage of catalog API requests and the majority of these requests show up in our logs as having no user-agent specified. It would make it much easier to track anomalous API traffic if we knew definitively which traffic was coming from the ODN.

**Comment by zang0** [comment]
To Tosh for direct cetera calls. Rest covered under https://github.com/socrata/odn-backend/issues/25

**Comment by ToshMeston** [comment]
Fixed.
