### ISSUE TITLE
use variable id not name in URLs

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#468]
see: http://opendatanetwork-staging-pr-467.herokuapp.com/region/0400000US53/Washington/population/annual_population_change/2013? 

should be

http://www.opendatanetwork.com/region/0400000US53/Washington/population/population_change/2013?

**Comment by ToshMeston** [comment]
@zang0 A variable ID looks like "demographics.population.change".  Is that what you want in the URL?  Replacing any instance of "." with "_"?

**Comment by chrismetcalf** [comment]
@zang0 Would http://www.opendatanetwork.com/region/0400000US53/Washington/demographics/population/change/2013 work for the `demographics.population.change` variable format? It's a nicely formatted friendly URL and maps directly to the variable name.

**Comment by ToshMeston** [comment]
Currently changed to use the variable ID as is.  I do like the idea the segments of the variable id become path segments, but that is a bigger change with SEO considerations.

**Comment by ToshMeston** [comment]
Assigned to @zang0 to think about.
