### ISSUE TITLE
Add "Return to..." back-linking and parameter

### ISSUE THREAD

**Issue by chrismetcalf** [socrata/opendatanetwork.com#473]
For custom integration with other Socrata properties, we want to be able to link into the ODN from other properties, and maintain a clear jump back to the original property. Can we add a feature like the following:

1. We accept two new parameters, similar to the [`x-callback-url`](http://x-callback-url.com/) scheme used in iOS:
    - `x-return-url`: The URL to return the user to. Ex: `https://finance.michigan.gov/`
    - `x-return-description`: The human readable source to return them to. Ex: `Michigan Finance`
2. Those values are then stored in a session cookie (not a persistent cookie, must expire at the end of their browser session)
3. If those values are present in the session cookie, we display a little box under the ODN logo in the upper left containing "Return to `$x-return-description`", hyperlinked to `x-return-url`

We should probably also store a white list of allowed return URL bases, but that may be a version 2.0 thing.

@ToshMeston Think this is something you can take on after you finish the API migration stuff?

@zang0 Any issues? This is for Michigan/Kyle

**Comment by chrismetcalf** [comment]
FYI, @kyleahall

**Comment by ToshMeston** [comment]
@chrismetcalf  Interesting.  We could have a very small "status bar"-like thing (20px in height or so and full browser width) above the top nav bar when there is something to go back to?  Very iOS-like.  Might be cool.

**Comment by kyleahall** [comment]
@ToshMeston Ideally, we'd make it a bit bigger - we were thinking either at the top of the nav on the left, or in the upper-right. 

![2016-08-12 at 10 42 am](https://cloud.githubusercontent.com/assets/19913510/17631611/a1d4e78a-6079-11e6-92a5-fd0855db730a.png)

**Comment by ToshMeston** [comment]
@kyleahall I would vote left over right.  That space under the logo would certainly work.

**Comment by kyleahall** [comment]
@ToshMeston Sounds good to me! I trust your eye. Just want to make sure it's big enough to be clearly seen.

**Comment by chrismetcalf** [comment]
Space under the logo was my first instinct too

**Comment by sasidharan-k** [comment]
completed and pushed changes to michigan_wip branch https://github.com/socrata/opendatanetwork.com/commit/d9e56f816f8b7ad3d3c218807452876b80687a37

**Comment by haibeeb** [comment]
Changed the param names to match the requested params above.  in commit: https://github.com/socrata/opendatanetwork.com/commit/a2c62c4418f109008ccd103cab85e5a9b6d6ef34

http://odn-staging-refactor.herokuapp.com/region/0500000US26035/finance?x-return-url=michigan.staging-insight-dashboard.socrata-qa.com&x-return-description=%22Return%20to%20Insight%20Dashboard%22
