### ISSUE TITLE
maps broken

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#477]
maps aren't rendering as choropleths. see attached image. console error:

2search.min.js:1 WebSocket connection to 'ws://api.opendatanetwork.com/data/v1/map/values' failed: Error during WebSocket handshake: Unexpected response code: 422

![screen shot 2016-08-15 at 1 00 55 pm](https://cloud.githubusercontent.com/assets/1051776/17677588/549eb8e4-62e8-11e6-9b1a-b959341cc9af.png)

**Comment by zang0** [comment]
Might be a network thing. Works fine for Tosh outside Socrata network, was failing for me in Indonesia but working from home.

**Comment by ToshMeston** [comment]
Yeah, working for me from home as well.

**Comment by zang0** [comment]
Any findings @chrismetcalf ??

**Comment by chrismetcalf** [comment]
Late update:

1. I repro exactly the same behavior on my machine, broken on the Socrata network with a `422` error, works when I VPN
2. Did some packet tracing with ElPato. The requests aren't being blocked at our local network, and he was able to reproduce it too
3. Digging in on the `422`s now, to see if they're server side or from the CDN

**Comment by zang0** [comment]
Per meeting - we'll focus on getting a solution that uses the non web sockets API when web sockets fail.

**Comment by zang0** [comment]
looks like @aaasen got this one. looks good.
