### ISSUE TITLE
drop down clicks in region menus fail

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#478]
go: http://opendatanetwork-staging.herokuapp.com/region/1600000US5363000/Seattle_WA/population/demographics.population.change/2013?
click on: 'population rate of change' and try to select 'population count'
note: fails to change url

repeat for any drop down combo, same thing.

**Comment by ToshMeston** [comment]
Somebody fixed this, but it wasn't me.

**Comment by ToshMeston** [comment]
Please close.
