### ISSUE TITLE
add map summary text above maps

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#479]
compare:

http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/population/demographics.population.change/2013?

w/ 

http://www.opendatanetwork.com/region/0400000US53/Washington/population/population_change/2013?

note: map summary text: "The population rate of change of Washington in 2013 was 1.2%." is not present - the summary for counts is present.

**Comment by ToshMeston** [comment]
I see the string on both.  Related to the websocket errors?  I believe this can be closed.

**Comment by zang0** [comment]
looks like it has the wrong summary, i.e. the one for count, not change.

**Comment by aaasen** [comment]
Fixed by #480
