### ISSUE TITLE
Create URL mapping from old URL structure to new one

### ISSUE THREAD

**Issue by chrismetcalf** [socrata/opendatanetwork.com#480]
Need to respect the old URL structure. Once done, make sure to restore the URL landing test below in tests/homepage-quicklinks.js

Here's the plan:

_1 fix the api such that desired JSON nodes and dataset id values are returned, see: https://github.com/socrata/odn-backend/issues/35

_2 new URLs should use the API stub instead of the old scheme. example:

/region/0400000US53/Washington/classroom_statistics/student_teacher_ratio/2014?

becomes:

/region/0400000US53/Washington/education.classroom_statistics.student-teacher-ratio/2014?

NOTE: for many cases, the returned API variable id is sufficient to generate the old URL such as in the above case where the returned API call from:

http://api.opendatanetwork.com/data/v1/availability/?entity_id=0400000US53&app_token=cQovpGcdUT1CSzgYk0KPYdAI0

returns variable id = "education.classroom_statistics.student-teacher-ratio"

_3 on the front end project, we maintain a mapping file for the differences (the cases where the variable id is not sufficient to generate the old URLs.) Example:

/region/0400000US53/Washington/education/high_school_graduation_rate/2013?

becomes:

/region/0400000US53/Washington/education.graduation_rate.percent_high_school_graduate_or_higher/2013?

in this case, the API will return (once https://github.com/socrata/odn-backend/issues/35 is fixed):

variable id = "education.graduation_rates.percent_high_school_graduate_or_higher"

so the leaf node: percent_high_school_graduate_or_higher does not match any known old URL variable equivalent, so we look it up in the mapping file:

percent_high_school_graduate_or_higher > high_school_graduation_rate

_4 using the above technique, we will forward all old URLs to the new URLs.

_5 all URLs on the site and generated sitemap including the homepage questions will use the new structure.

_6 we make repeated full passes comparing all region type > topic > sub topic permutations, we update the mapping file to catch any misses, and repeat until we feel comfortable all URLs are covered.

_7 we add a release test that validates a sample of old URLs are forwarded correctly to the new URLs.

 

/** @TODO TEST FAILS, FIX OR DELETE IT casper.then(function() {
        casper.clickLabel('California');
    });

    casper.then(function() {
        casper.wait(5000, function() {
          test.assertUrlMatch(/region\/0400000US06\/California\/population\/population\/2013/, 'Verifies that a click on California from the homepage lands on this URL structure');
          casper.back();
        });
    });*/

**Comment by ToshMeston** [comment]
What did we decide to do here?  The last I heard we did not want to change from the prod URL structure? @zang0 @chrismetcalf

**Comment by zang0** [comment]
Okay, I rewrote the issue definition. Take a look @ToshMeston @aaasen @chrismetcalf and see if there are any problems folks can think of.

**Comment by aaasen** [comment]
Structure that I am currently implementing:

```
/entity/{entity ids}/{entity names}/{topic, dataset, or variable id}
```

The following are all valid URLs:

```
/entity/0400000US53
/entity/0400000US53/Washington
/entity/0400000US53/Washington/demographics
/entity/0400000US53/Washington/demographics.population
/entity/0400000US53/Washington/demographics.population.count
```

Constraints are passed in as query parameters. For example:

```
/entity/0400000US53/Washington/demographics.population.count?year=2013
/entity/0400000US53/Washington/health.health_indicators?question=Adults_that_have_had_any_permanent_teeth_extracted&year=2011&question_response=No&break_out=15000_24999
```

I decided to move the endpoint from `/region` to `/entity` to make it easier to distinguish between old and new links. The name should change anyway since we have generalized regions to entities.

These URLs are functional on #511 and I am currently working on redirecting old URLs.

**Comment by aaasen** [comment]
Also, entity names are just for SEO. They are not used at all so links will still work even if the names are corrupted.

**Comment by aaasen** [comment]
Merged into staging. Some issues:
 - [ ] implement infinite scroll on dataset results (must add `/search-results` endpoint)
 - [ ] restore quick links (do we really need these?)
 - [x] fix autosuggest link targets being to small
 - [ ] restore API badges
 - [ ] restore show more questions
 - [ ] improve error page for missing datasets, variables, etc.
 - [ ] update home page links
 - [ ] fix travis build
 - [ ] fix questions referencing incorrect variables
 - [ ] fix menus overflowing on datasets with many constraints
 - [x] health indicator question menu not working (some string escaping)

**Comment by aaasen** [comment]
Added redirects from old `/region` links. Configuration is here: https://github.com/socrata/opendatanetwork.com/tree/staging/app/controllers/redirect

My testing was pretty thorough and I'm confident that all of the old links will redirect properly.

**Comment by aaasen** [comment]
There are still some unresolved issues that were created by this ticket, but the ticket itself is done so I'm closing and filing new tickets for the other issues.
