### ISSUE TITLE
add maps api badge

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#481]
currently no way to show the maps data calls. lets add a badge to the right of the map summary sentence: "The gdp per capita of Seattle Metro Area (WA) in 2013 was $74,701."

Should say:

/data/v1/map/new (links to: http://docs.odn.apiary.io/#reference/0/map-creation)
/data/v1/map/values (links to: http://docs.odn.apiary.io/#reference/0/map-data)

Examples:

Create a new map for Seattle Metro Area
Get data for a map for Seattle Metro Area

API docs:

Create a new map (links to: http://docs.odn.apiary.io/#reference/0/map-creation/create-a-map)
Get data for a map (links to: http://docs.odn.apiary.io/#reference/0/map-data/get-map-data)

Feel free to display the 2 calls sequentially if its easier.

<img width="769" alt="screen shot 2016-08-15 at 5 04 24 pm" src="https://cloud.githubusercontent.com/assets/1051776/17683712/5542e8ca-630a-11e6-9e5e-49fe2babd6dd.png">

**Comment by ToshMeston** [comment]
Fixed.  Note that the API link to get the map data needs the session_id and bounds returned by the new map call, so I've just left session_id=[SESSION_ID_FROM_MAP_NEW_CALL] in the URL as well as sample bounds coordinates so they can see the correct order.
