### ISSUE TITLE
change numeric sort order big>small

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#483]
see attached images, staging vs prod
![screen shot 2016-08-16 at 7 14 30 pm](https://cloud.githubusercontent.com/assets/1051776/17722258/b478469c-63e5-11e6-96e2-774cd4da2580.png)
![screen shot 2016-08-16 at 7 14 24 pm](https://cloud.githubusercontent.com/assets/1051776/17722259/b47d7ba8-63e5-11e6-8c9f-5cb66782948e.png)

**Comment by ToshMeston** [comment]
Fixed.
