### ISSUE TITLE
Why is the FBI UCR data reporting the wrong numbers for historical years

### ISSUE THREAD

**Issue by chrismetcalf** [socrata/opendatanetwork.com#484]
Loading up the FBI UCR data for Flint, MI:

http://rc-opendatanetwork.herokuapp.com/region/1600000US2629000/Flint_MI/fbi_ucr/crime.fbi_ucr.count/2014?

Only the 2014 number is correct for "All Crimes". For older years, it seems to be using the smaller value for "Forcible rape" instead.

The raw data looks correct:

GET https://odn.data.socrata.com/resource/eds5-udzt.json?id=1600000US2629000&crime_type=All%20Crimes&$select=year,%20name,%20value&variable=count&$order=year

What's going on? Is it a configuration error with my dataset, or maybe a bug in socrata/odn-backend or the charting layer?

**Comment by chrismetcalf** [comment]
FYI @kyleahall

**Comment by kyleahall** [comment]
Also FYI @haibeeb

**Comment by chrismetcalf** [comment]
@aaasen added the proper constraints to the FBI dataset, so you can now filter the ODN API and get the appropriate constraints back: http://api.opendatanetwork.com/data/v1/values?app_token=cQovpGcdUT1CSzgYk0KPYdAI0&entity_id=1600000US2629000&format=google&variable=crime.fbi_ucr.count&crime_type=All%20Crimes

However, the charts still aren't populating the constraints in the queries, so the actual UCR region pages are failing to load now. That's the same bug as @ToshMeston's https://github.com/socrata/opendatanetwork.com/issues/500

**Comment by ToshMeston** [comment]
The data values requests to populate the charts require a constraint.  I've specified the year constraint in dataset-config.js and made these chart types column, instead of line.

Fixed.
