### ISSUE TITLE
Clean up Michigan data taxonomy

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#485]
Lets:

_1 replace 'Michigan' as a high level category, with the new category "Finance" which we will be using throughout the site. 

_2 replace "Michigan Financial Indicators" with appropriate subcategories for Finance. Something like:

-Revenue
--includes: Long Term Debt Revenue
--includes: Total General Fund Revenue
--includes: Unrestricted Revenue
-Expenses
--includes: Total General Fund Expenditures
-One or more other sub categories that groups the others.  Kyle, can you propose something -- I can't see the data yet, and don't quite understand what these should be.

**Comment by kyleahall** [comment]
@zang0 This data is MI-specific and not necessarily ever likely to be comparable across state lines. I'd actually prefer for us to call the subcategory "MICommunity Financial Indicators" (name of the MI dashboard) to house these metrics, and add nationally comparable finance information from Census in more generic subcategories.

**Comment by zang0** [comment]
Chatted w/ @kyleahall on this. I believe we agreed to have Finance>Michigan Financial Indicators>[the rest]

**Comment by haibeeb** [comment]
Kicking this over to @kyleahall as a json configuration fix with Alicia.

**Comment by kyleahall** [comment]
@aliciatb This is done, correct? Can we close out?

**Comment by aaasen** [comment]
This is done and deployed to the backend. Charts will need to be updated on the frontend: https://github.com/socrata/opendatanetwork.com/blob/staging/src/dataset-config.js#L17

**Comment by zang0** [comment]
closing this. opening individual tickets. @kyleahall have a look as its not quite what we discussed, but it is in line w/ ODN norms, and i think it aligns w/ what you were after. file specific changes as independent tickets if you need them.
