### ISSUE TITLE
wrong source on mi pages

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#486]
note: source points to fbi data

![screen shot 2016-08-18 at 1 37 08 pm](https://cloud.githubusercontent.com/assets/1051776/17789879/ef10beb0-6548-11e6-8d88-338c14ab2edb.png)

**Comment by kyleahall** [comment]
Correct source is "MICommunity Financial Dashboard," and links to mi-treasury.data.socrata.com

**Comment by haibeeb** [comment]
Fixed. http://opendatanetwork-staging.herokuapp.com/region/0500000US26163/Wayne_County_MI/finance/michigan.finance.total_general_fund_expenditures/2016?
