### ISSUE TITLE
change chart api badge to /values

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#489]
_1 should be 

/data/values

not

/data/availability Endpoint

_2

Variable IDs:
demographics.population.count for Seattle, WA

API Docs:
Find all available data for some entities

should read

Example:
Get demographics.population.count values for Seattle, WA

(no link on demographics.population.count and only one on Seattle, WA to: /values call)

API Docs:
Get values for variables

(links to: http://docs.odn.apiary.io/#reference/0/data-values/get-values-for-variables)

![screen shot 2016-08-19 at 3 38 12 pm](https://cloud.githubusercontent.com/assets/1051776/17826178/0704d1de-6623-11e6-9be7-872efce8a27c.png)

**Comment by ToshMeston** [comment]
Fixed.

**Comment by zang0** [comment]
looks good
