### ISSUE TITLE
timeseries charts not populating

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#491]
see: 

http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/cost_of_living/economy.cost_of_living.rank/2008?

or

http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/cost_of_living/economy.cost_of_living.index/2008?

**Comment by ToshMeston** [comment]
Fixed.

**Comment by zang0** [comment]
looks good.
