### ISSUE TITLE
not all variables returned are appearing in the comparison charts

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#492]
see:

http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/education/education.education.percent_graduate_or_professional_degree/2013?

note: 

all options under the tier 3 category menu should appear in the comparison chart. Only those previously launched to prod do.

We need: 

_1 the tier 3 category drop down (e.g. Adult Obesity Rate) AND what appears in the tables should ALWAYS be identical

_2 default behavior where NO whitelist is supplied takes all variables returned from the API and populates the nav and table

_3 an optional UI layer whitelist that populates  the nav and table using only the whitelisted variables.

Note: The whitelist is required because some datasets appear to populate multiple menu permutations. See: Health Behaviors and Health Indicators, both yanked from "fxf": "csbu-um39".

Validation: once done, apply the whitelist to: http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/health/health.health.adult_obesity_value/2015? such that the table is retained, and the chart matches (so all the extra vars are gone)

<img width="766" alt="screen shot 2016-08-24 at 10 57 51 am" src="https://cloud.githubusercontent.com/assets/1051776/17941783/a0e71d6a-69e9-11e6-8ac8-a57d62ea43ff.png">

**Comment by zang0** [comment]
per convo, want 1 config for both

**Comment by aaasen** [comment]
Fixed by #480
