### ISSUE TITLE
Source citation signatures incomplete

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#493]
See attached images. Compare: 

http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/health/health.health.adult_obesity_value/2015?
sig=Above charts are based on data from the Robert Wood Johnson Foundation

to

http://www.opendatanetwork.com/region/0400000US53/Washington/health/adult_obesity_rate/2015?
sig=Above charts are based on data from the Robert Wood Johnson Foundation | Data Source | ODN Dataset | API - i

Note: the mouseover behavior on the i we also want to retain. Staging and Prod should be identical.

**Comment by ToshMeston** [comment]
Fixed

**Comment by zang0** [comment]
Missing the API link to the right of the ODN Dataset

**Comment by ToshMeston** [comment]
Oops.  Fixed.
