### ISSUE TITLE
Missing (Forecasted) in Mouseover on forecasted data points

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#494]
See prod vs staging attached screenshots.
![screen shot 2016-08-25 at 10 54 31 am](https://cloud.githubusercontent.com/assets/1051776/17980028/58289af8-6ab2-11e6-8d51-008a99083387.png)
![screen shot 2016-08-25 at 10 54 20 am](https://cloud.githubusercontent.com/assets/1051776/17980029/583b18ae-6ab2-11e6-9763-aecb2cea7c80.png)

**Comment by ToshMeston** [comment]
@aaasen Hey Lane, I changed the charts over to use a format=google.  Is there a way to have the "(Forecasted)" applied server-side when "forecast=X" is specified?

**Comment by aaasen** [comment]
Fixed in backend.

**Comment by zang0** [comment]
can you explain where this change is? i stared at this one for a while and remain clueless.

**Comment by aaasen** [comment]
The backend will now add Measured and Forecasted if `format=google`. For example: http://odn-backend-staging.herokuapp.com/data/v1/values?variable=demographics.population.count&entity_id=0100000US&forecast=3&app_token=cQovpGcdUT1CSzgYk0KPYdAI0&format=google

It isn't deployed to backend production yet.
