### ISSUE TITLE
don't fill in area on bar charts

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#495]
see

http://opendatanetwork-staging.herokuapp.com/region/0500000US53033-0500000US53061/King_County_WA-Snohomish_County_WA/earnings/jobs.earnings.median_earnings/2013?

vs

http://www.opendatanetwork.com/region/0500000US53061-0500000US53053/Snohomish_County_WA-Pierce_County_WA/earnings/median_earnings/2013?
![screen shot 2016-08-25 at 11 02 23 am](https://cloud.githubusercontent.com/assets/1051776/17980305/7f996fe4-6ab3-11e6-99ce-024c723146f2.png)
![screen shot 2016-08-25 at 11 02 13 am](https://cloud.githubusercontent.com/assets/1051776/17980306/7f9f34a6-6ab3-11e6-9034-6af9101d0120.png)

**Comment by ToshMeston** [comment]
Fixed.
