### ISSUE TITLE
initial landing has no map summary sentence

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#498]
go to:

http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)

or autosuggest to seattle metro

note summary sentence above the map 

is not there. now, choose tier 3 option 'Population Rate of Change' - note: summary sentence is present, but its the wrong one.

The population count of Seattle Metro Area (WA) in 2013 was 3,504,628.

![screen shot 2016-08-26 at 10 43 30 am](https://cloud.githubusercontent.com/assets/1051776/18014965/472fcc94-6b7a-11e6-9bd9-5b6730089ab0.png)
![screen shot 2016-08-26 at 10 43 17 am](https://cloud.githubusercontent.com/assets/1051776/18014964/472ecdc6-6b7a-11e6-9866-62d0ccd46453.png)

**Comment by aaasen** [comment]
Fixed by #480
