### ISSUE TITLE
homepage clicks on categories lost the ref=hp parameter

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#499]
http://opendatanetwork-staging.herokuapp.com/search?categories=infrastructure

is the resulting URL from a homepage click on infrastructure. 

should be /search?categories=infrastructure&ref=hp

once fixed, please restore the test in tests/homepage-quicklinks.js and ensure they pass

**Comment by ToshMeston** [comment]
Fixed.
