### ISSUE TITLE
page toggles not generating all constraint permutations, so no map appearing

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#500]
go to: http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/cost_of_living/economy.cost_of_living.index/2013?

note: no map

note: map error: https://odn-backend.herokuapp.com/data/v1/map/new?variable=economy.cost_of_living.index&entity_id=310M200US42660&app_token=cQovpGcdUT1CSzgYk0KPYdAI0&year=2013

{"error":{"message":"must specify values for constraints: component"},"statusCode":422,"url":"/data/v1/map/new?variable=economy.cost_of_living.index&entity_id=310M200US42660&app_token=cQovpGcdUT1CSzgYk0KPYdAI0&year=2013"}

what we want is a drop down for every constraint in the /availability call. note, in this case there are 2, year and component. The drop down values should contain all of the permutations for that constraint using this call: 

http://api.opendatanetwork.com/data/v1/constraint/demographics.population.count?entity_id=310M200US42660&constraint=year&app_token=cQovpGcdUT1CSzgYk0KPYdAI0

where the UI picks the order and default.

**Comment by zang0** [comment]
Validate this case works before closing: https://github.com/socrata/odn-backend/issues/34

**Comment by aaasen** [comment]
Fixed and deployed to staging.

**Comment by zang0** [comment]
Re-opening, few issues:

_1 - not sure if this one is related: https://github.com/socrata/opendatanetwork.com/issues/508

_2 - lets move the year drop down to the far right

_3 - year drop downs no longer sort most recent year to least

**Comment by aaasen** [comment]
Fixed 2 and 3, 1 covered by #508 so closing.
