### ISSUE TITLE
crime maps not appearing

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#504]
http://opendatanetwork-staging.herokuapp.com/region/1600000US5363000/Seattle_WA/fbi_ucr/crime.fbi_ucr.rate/2014?

**Comment by bewithjonam** [comment]
Same as https://github.com/socrata/opendatanetwork.com/issues/500

There are multiple constraints year/crime_type and we are passing only year to the v1/map/new api call.

**Comment by chrismetcalf** [comment]
@bewithjonam is correct. When we added the proper constraint setups to the FBI crime map data, the maps broke, since the constraints weren't being passed in from the nav to the API.

**Comment by aaasen** [comment]
Fixed in #500
