### ISSUE TITLE
More Info not hidden in mobile view

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#506]
http://opendatanetwork-staging.herokuapp.com/region/0100000US/United_States/occupations/jobs.occupations.percent_employed/2013?

shrink to mobile size or access on device
note stuff below is visible by default. Should require click as it does in full size mode.

More Information
Computers and Math Employment Rate
Construction and Extraction Employment Rate
Education Employment Rate
Engineering Employment Rate
Farming, Fishing, Foresty Employment Rate
Fire Fighting Employment Rate
Food Service Employment Rate
Healthcare Employment Rate
Health Support Employment Rate
Health Technicians Employment Rate
Janitorial Employment Rate
Law Enforcement Employment Rate
Legal Employment Rate
Management Employment Rate
Material Moving Employment Rate
Media Employment Rate
Office and Administration Employment Rate
Personal Care Employment Rate
Production Employment Rate
Repair Employment Rate
Sales Employment Rate
Social Sciences Employment Rate
Social Services Employment Rate
Transportation Employment Rate

**Comment by ToshMeston** [comment]
Fixed.
