### ISSUE TITLE
landing sentence not using API call

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#507]
go to:
http://opendatanetwork-staging.herokuapp.com/region/310M200US42660/Seattle_Metro_Area_(WA)/occupations/jobs.occupations.employed?occupation=Business%20and%20Finance

note: the summary sentence is not coming from the back end. it should, and once the ticket below is fixed, should be correct.

https://github.com/socrata/odn-backend/issues/36

**Comment by aaasen** [comment]
Fixed by #480
