### ISSUE TITLE
crime charts not populating

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#508]
goto: http://opendatanetwork-staging.herokuapp.com/region/1600000US5363000/Seattle_WA/fbi_ucr/crime.fbi_ucr.count/2014?crime_type=Arson

note: charts have no data

{"error":{"message":"must specify values for all but one of: year, crime_type"},"statusCode":422,"url":"/data/v1/values?variable=crime.fbi_ucr.count&entity_id=1600000US5363000&app_token=cQovpGcdUT1CSzgYk0KPYdAI0"}

**Comment by aaasen** [comment]
Looks like @ToshMeston fixed this with 64008acd5a2759241d1082da90032664f4aa5dc5
