### ISSUE TITLE
Restore API Badges

### ISSUE THREAD

**Issue by aaasen** [socrata/opendatanetwork.com#515]
API badges were lost on #480. They were poorly implemented - hard coded in templates. Refactor to client and use new ODN client library to generate links.

**Comment by zang0** [comment]
badges on homepage next to geo regions disappeared

**Comment by ToshMeston** [comment]
Man.  The infoboxes were implemented in template for two reasons - 1) Search engine discoverability  2) Having them in DOM, but hidden, lets you run the nice slide animation.

**Comment by aaasen** [comment]
We don't need the API badges to be discovered by the search engine. They just point to the backend and apiary. The slide animations could still be implemented without the API boxes in templates but we don't need them.

**Comment by ToshMeston** [comment]
Some of the infoboxes had additional information or different descriptions.  For instance, the Map info-box had info on New and Data.  Now we have New only.

**Comment by aaasen** [comment]
We decided to exclude map data since it is now only available over websockets.

**Comment by zang0** [comment]
closing this, rest covered by other tickets now.
