### ISSUE TITLE
x to nix compare choices colors are off

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#523]
https://opendatanetwork-staging.herokuapp.com/entity/310M200US28140-310M200US33460-310M200US42660/Kansas_City_Metro_Area_MO_KS-Minneapolis_Metro_Area_MN_WI-Seattle_Metro_Area_WA/economy.gdp.per_capita_gdp?

note the x to drop a metro in the upper left pane are purple. used to be less eye attracting blue of the text color.

**Comment by ToshMeston** [comment]
Fixed.
