### ISSUE TITLE
forecast not present for seattle metro economy.gdp.per_capita_gdp

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#526]
https://opendatanetwork-staging.herokuapp.com/entity/310M200US42660/Seattle_Metro_Area_WA/economy.gdp.per_capita_gdp?

note: no forecast is displayed in the UI despite the API call 

https://api.opendatanetwork.com/data/v1/values?app_token=cQovpGcdUT1CSzgYk0KPYdAI0&describe=true&forecast=5&format=google&variable=economy.gdp.per_capita_gdp&entity_id=310M200US42660

returning one:

"The last measured GDP per capita for Seattle Metro Area (WA) was $74,701 for 2013. Seattle Metro Area (WA) experienced an average growth rate of 1.2% from our first statistic recorded in 2001. If past trends continue, we forecast the GDP per capita to be $78,962 by 2018."

**Comment by ToshMeston** [comment]
Fixed.
