### ISSUE TITLE
freaky colors in "compare this data" drop down

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#527]
https://opendatanetwork-staging.herokuapp.com/entity/1600000US0820000-1600000US4159000-1600000US5363000/Denver_CO-Portland_OR-Seattle_WA/crime?

type in compare this data drop down

![screen shot 2016-09-07 at 11 22 10 am](https://cloud.githubusercontent.com/assets/1051776/18323656/6e1fe380-74ed-11e6-9140-f87aa0e08bd5.png)

**Comment by ToshMeston** [comment]
Fixed CSS.

Note: There should only be regions in this autosuggest menu.
