### ISSUE TITLE
compare this additions fail

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#528]
go to https://opendatanetwork-staging.herokuapp.com/entity/1600000US5363000/Seattle_WA?
type in and select chicago, il under compare this data
note: 

page went to: https://opendatanetwork-staging.herokuapp.com/entity/1600000US1714000/Chicago_IL?

not a comparison page

**Comment by ToshMeston** [comment]
@zang0 I am assuming this can be punted as the Compare this Data textbox is gone?

**Comment by zang0** [comment]
punting pending #54 in odn-backend
