### ISSUE TITLE
chart resolution off for crime incidents

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#529]
https://opendatanetwork-staging.herokuapp.com/entity/1600000US1714000-1600000US0644000-1600000US5363000/Chicago_IL-Los_Angeles_CA-Seattle_WA/crime.fbi_ucr.rate?crime_type=Aggravated+assault&year=2014

mouseover incident rates, note: all say 0. Y axis is wrong too, should be a number of crimes per 100k, like 234.3 not .012

![screen shot 2016-09-07 at 11 37 00 am](https://cloud.githubusercontent.com/assets/1051776/18324093/8243d5f4-74ef-11e6-96c0-f795ec444721.png)

**Comment by chrismetcalf** [comment]
@aaasen Is this something that would be fixed with the proper type on the `rate` variable? Is that in `odn-backend`'s `sources.json`?

**Comment by chrismetcalf** [comment]
@aaasen Shouldn't `type: "rate"` fix this?

https://github.com/socrata/odn-backend/blob/master/data/sources.json#L356

**Comment by zang0** [comment]
test it locally, but doesn't look like it's fixed. see: https://opendatanetwork-staging.herokuapp.com/entity/1600000US5363000/Seattle_WA/crime.fbi_ucr.count?crime_type=Murder%20and%20nonnegligent%20manslaughter&year=2014

mouseover any bars on the lower chart.

to test locally:

-const _ODN_API_HOST_AND_PORT = 'api.opendatanetwork.com';
-const _ODN_API_BASE_URL = 'https://'+_ODN_API_HOST_AND_PORT;
+const _ODN_API_HOST_AND_PORT = 'localhost:3001';
+const _ODN_API_BASE_URL = 'http://'+_ODN_API_HOST_AND_PORT;

in odn.com - src/constants.js and fire up a odn-backend server

**Comment by chrismetcalf** [comment]
In CR at https://github.com/socrata/odn-backend/pull/62

@aaasen Can you approve the PR? Works locally, but I want you to confirm the method and new `type` name.

**Comment by aaasen** [comment]
@chrismetcalf Merged your PR into master. Looks like your fix worked.
