### ISSUE TITLE
year for bar charts should be included

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#530]
https://opendatanetwork-staging.herokuapp.com/entity/1600000US1714000-1600000US0644000-1600000US5363000/Chicago_IL-Los_Angeles_CA-Seattle_WA/crime.fbi_ucr.count?crime_type=all_crimes&year=2013

note: the bar charts do not state the year. lets include in the charts source citation. Something like: Bar charts are based on data from 2013.

**Comment by chrismetcalf** [comment]
Closed in #531
