### ISSUE TITLE
improve fbi source citation

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#531]
can we improve the source citation so it points to the actual data instead of the high level page? its pretty tough to get to the actual table that confirms or denies the data integrity. right now, i can't tell if our data is accurate against other sources. if not in the product, than prove to me somehow that what we are showing is legitimate as i'm finding many cases where it varies from other folks claiming fbi data.

**Comment by zang0** [comment]
add a sentence to stating something like: Chart data is from FBI UCR 2014.:

Crime statistics are sourced from the FBI Uniform Crime Reporting Program and aggregated across year and crime type. The FBI does not gather statistics for all jurisdictions, so some localities may be missing. Normalization is based on the population values published with the UCR data itself, so rather than on US Census data, as the jurisdiction of the data may vary. Crime rates are normalized on a per 100K basis; specifically, the crime count is divided by the population count, the result is then multiplied by 100K and rounded to the nearest integer value.

**Comment by chrismetcalf** [comment]
Change pushed to socrata/odn-backend staging.
