### ISSUE TITLE
400 on zip code 

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#532]
go to: https://opendatanetwork-staging.herokuapp.com/entity/1600000US1714000/Chicago_IL/crime.fbi_ucr.count?crime_type=Aggravated%20assault&year=2014

now search for 98115 and select

https://opendatanetwork-staging.herokuapp.com/entity/8600000US98115/98115_ZIP_Code/jobs.earnings.percent_with_earnings_1_to_9999?year=2013

note: 400

**Comment by aaasen** [comment]
Fix is deployed to backend staging. Will close when it is deployed to prod.

**Comment by aaasen** [comment]
Fix deployed to backend production. Example here: https://opendatanetwork-staging.herokuapp.com/entity/8600000US98115/98115_ZIP_Code/jobs.earnings.percent_with_earnings_1_to_9999?year=2013
