### ISSUE TITLE
mobile popped

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#533]
No menus when you reduce this width.
https://opendatanetwork-staging.herokuapp.com/entity/310M200US42660/Seattle_Metro_Area_WA/economy.gdp.per_capita_gdp?year=2013

**Comment by zang0** [comment]
lets make sure we restore our hard won mobile gains.

**Comment by aaasen** [comment]
I've restored the menus on entity pages. Will deploy soon. I also have to restore menus on search pages. Both had to be changed significantly to support the new URL structure.
