### ISSUE TITLE
change default map landing up a zoom level for counties

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#535]
go to: https://opendatanetwork-staging.herokuapp.com/entity/0500000US53033/King_County_WA/jobs.job_proximity.jobs-prox-idx-mean?year=2015

note: zoom level is far in

should be something like the attached image. think this is only happening w/ counties for some reason.

![screen shot 2016-09-08 at 9 54 32 am](https://cloud.githubusercontent.com/assets/1051776/18358547/679f6ec8-75aa-11e6-8ea4-446fe423e71e.png)
![screen shot 2016-09-08 at 9 54 18 am](https://cloud.githubusercontent.com/assets/1051776/18358548/67a23478-75aa-11e6-9791-17daf2df2fc3.png)

**Comment by aaasen** [comment]
Fixed this. You can adjust the padding used for auto zoom here: https://github.com/socrata/opendatanetwork.com/blob/staging/src/maps/constants.js#L39
