### ISSUE TITLE
question clicks blow up

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#536]
https://opendatanetwork-staging.herokuapp.com/entity/0500000US53033/King_County_WA/jobs.job_proximity.jobs-prox-idx-mean?year=2015

click on either question, note the 404

also, we shouldn't show the question whose page we're already on as a recommended question.

**Comment by aaasen** [comment]
The links will no longer give 404s, but fixing the issue of showing redundant questions is a bit difficult since questions use old variables.

**Comment by zang0** [comment]
latter part is in #537
