### ISSUE TITLE
don't show current page in questions list

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#537]
we shouldn't show the question whose page we're already on as a recommended question

https://opendatanetwork-staging.herokuapp.com/entity/0500000US53033/King_County_WA/jobs.job_proximity.jobs-prox-idx-mean?year=2015

**Comment by aaasen** [comment]
Questions now look like this: 

![image](https://cloud.githubusercontent.com/assets/1320603/18369851/2bde2de2-75dd-11e6-8e37-f5c3406da545.png)

They now link to every selected entity instead of just the first one like in production.

Question relevance should improve when #538 is fixed.

**Comment by zang0** [comment]
looks good
