### ISSUE TITLE
sort non year drop downs

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#538]
![screen shot 2016-09-08 at 12 40 56 pm](https://cloud.githubusercontent.com/assets/1051776/18364014/837068b6-75c1-11e6-927c-036cad15b492.png)
![screen shot 2016-09-08 at 12 40 08 pm](https://cloud.githubusercontent.com/assets/1051776/18364015/837128be-75c1-11e6-80c6-304f260c7b86.png)

**Comment by zang0** [comment]
+ @aaasen . anyone have a preference if its front end or back end? seems like if we do it in the back end we spare other clients the work for what seems like the obvious way to display.

**Comment by ToshMeston** [comment]
Prefer server.

**Comment by aaasen** [comment]
Backend will now respect the sorting of variables in `sources.json`.
