### ISSUE TITLE
others in X badges disappeared

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#543]
others in X badges also look like they disappeared, unless i'm hallucinating, e.g. others in washington: https://opendatanetwork-staging.herokuapp.com/entity/1600000US5363000/Seattle_WA?

**Comment by aaasen** [comment]
Fixed this, but sometimes the API badge overflows onto the next line.

![image](https://cloud.githubusercontent.com/assets/1320603/18369913/a158a84a-75dd-11e6-919a-b33c3be8f1c3.png)

@ToshMeston wondering if you know how to fix this? Only change that I made to the HTML was adding a `<div>` around each section header e.g. "Counties in Washington".
