### ISSUE TITLE
FBI UCR: Data for Washington, DC missing for 2009-2012

### ISSUE THREAD

**Issue by chrismetcalf** [socrata/opendatanetwork.com#544]
https://www2.fbi.gov/ucr/cius2009/data/table_08_dc.html

**Comment by zang0** [comment]
is this dropped in your script or src data?

**Comment by chrismetcalf** [comment]
Fixed in https://github.com/socrata/odn-backend/pull/66

**Comment by chrismetcalf** [comment]
Fixed (https://opendatanetwork-staging.herokuapp.com/entity/1600000US1150000/Washington_DC/crime.fbi_ucr.count?crime_type=Aggravated%20assault&year=2014)
