### ISSUE TITLE
FBI UCR: Data missing for Alburtis, PA

### ISSUE THREAD

**Issue by chrismetcalf** [socrata/opendatanetwork.com#546]
https://opendatanetwork-staging.herokuapp.com/entity/1600000US4200660/Alburtis_PA/crime.fbi_ucr.count?crime_type=All%20Crimes&year=2006

2007, 2010-2013

**Comment by zang0** [comment]
how prolific is this prob? feels well handled by the UI and late to re-run.

**Comment by chrismetcalf** [comment]
Been digging in on this this afternoon. Based on some queries, it doesn't seem to be an _uncommon_ case where a city name from the UCR doesn't have a match against our places DB, or where the city name changes from year to year, "Alburtis, PA" vs "Alburtis Township, PA" for example. There are also a good number towns the UCR has that we don't have in our places DB. And lets not start on "Owens Town" vs "Owenstown" and things like that. 

When we get a match, the numbers are solid. I built the script to fail-safe, and not miss-match data to the wrong city.

The UI does handle it very well, so I wouldn't consider this a blocking issue.

I'm experimenting with the script to remove "stop words" like "city", "township", "borough", etc. to improve matching, hopefully without ending up with dupes. I can build a second version of the dataset we can compare and test against.

**Comment by chrismetcalf** [comment]
The Commonwealth of PA and the FBI seem to not like to agree on what cities to count, there are a lot of complete misses in that state.

**Comment by zang0** [comment]
punt

**Comment by chrismetcalf** [comment]
Fixed in https://github.com/socrata/odn-backend/pull/66

Comparing [old](https://dev.socrata.com/foundry/odn.data.socrata.com/eds5-udzt) and [new](https://dev.socrata.com/foundry/odn.data.socrata.com/rzhy-aw2m), the new version has almost 10% more entries, and includes better coverage for places that had high miss rates like PA and DC.

There are still many cities that don't have matches in either direction. The ACS doesn't include many of the cities in the UCR, and vice versa, so there are many matches to burn down. An audit log of mismatches in either direction is in this private dataset: https://odn.data.socrata.com/dataset/FBI-UCR-V3-Audit-Log/ye3j-8h3t

**Comment by chrismetcalf** [comment]
Fixed! 🎉
