### ISSUE TITLE
autosuggest>question yields 404

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#547]
https://opendatanetwork-staging.herokuapp.com/entity/0400000US21/Kentucky/health.health.adult_obesity_value?

type in kentucky

choose "What is the adult obesity rate of Kentucky"

note 404

**Comment by aaasen** [comment]
This was an issue with redirecting to the wrong urls after we renamed some datasets. It may appear that the issue was not resolved since browsers cache 301 redirects.
