### ISSUE TITLE
drop down perms don't equal table for king county/jobs/occupations

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#549]
go to: https://opendatanetwork-staging.herokuapp.com/entity/0500000US53033/King_County_WA/jobs.occupations.percent_employed?occupation=Business%20and%20Finance&year=2013

click occupations list drop down
note there are a bunch
scroll down
look @ the table
note: there are 5

rest got dropped somewhere 

![screen shot 2016-09-08 at 5 19 59 pm](https://cloud.githubusercontent.com/assets/1051776/18371365/ae8f6372-75e8-11e6-9680-7d60b4b54cf1.png)
![screen shot 2016-09-08 at 5 19 52 pm](https://cloud.githubusercontent.com/assets/1051776/18371366/aea029f0-75e8-11e6-97e4-e4e6980b6666.png)

**Comment by aaasen** [comment]
It looks like they aren't getting dropped, the table height is just too small. Fixed by removing `height: 300` from default chart configuration.
