### ISSUE TITLE
bar chart not showing tiny numbers

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#551]
see:

https://opendatanetwork-staging.herokuapp.com/entity/1600000US5363000/Seattle_WA/crime.fbi_ucr.count?crime_type=Murder%20and%20nonnegligent%20manslaughter&year=2014

note: thats 79 arsons per the api call, but you can't mouseover and see the actual arson count in the first bar chart. can we add a mouseover target on the label too? or some other way to shake the chart a bit?

**Comment by ToshMeston** [comment]
Switched to bar charts so there is more room to draw the small bars and hover over them.  Fixed.

**Comment by ToshMeston** [comment]
Perhaps an annotation role with line style can be added to show something for these very small bars.  https://developers.google.com/chart/interactive/docs/roles

**Comment by aaasen** [comment]
Found and implemented this fix: http://stackoverflow.com/questions/33801218/google-charts-column-chart-how-can-i-show-a-tooltip-when-the-value-is-so-small
