### ISSUE TITLE
MI src citations are broken

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#552]
go to:

https://opendatanetwork-staging.herokuapp.com/entity/1600000US2642160/Kalamazoo_MI/finance.michigan_property_tax.property_tax_health?year=2015

scroll to bottom and click on ODN Dataset and API links:

note: This dataset or view cannot be found, or has been deleted.

wrong dataset handles provided

**Comment by aliciatb** [comment]
https://mi-treasury.data.socrata.com/dataset/Indicators/qvun-6ew5 is the right dataset and the domain property is set like this. Is there another configuration required for datasets not on the ODN domain?
```
"fxf": "qvun-6ew5",
"domain": "mi-treasury.data.socrata.com",
```

**Comment by aliciatb** [comment]
Just committed https://github.com/socrata/odn-backend/commit/fd4a3b630e8cd2f72fd495b36b2920e6f3a207b6 setting domain on all other indicators
```
 "domain": "odn.data.socrata.com",
```

**Comment by haibeeb** [comment]
Fixed in commit: https://github.com/socrata/opendatanetwork.com/commit/67369b10600364302a43796372a7d9756cb604e5

@zang0 @kyleahall can you verify and close?
