### ISSUE TITLE
MI clean up maps

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#555]
https://opendatanetwork-staging.herokuapp.com/entity/1600000US2622000/Detroit_MI/finance.michigan_pensions.pension_health?year=2013

not sure what -9142$ pension health means, but my guess is its worse than Warren county which is 1361$. So, sweep through all the maps, and use the stoplight=true and reverse=true properties where appropriate. we use stop lights wherever numbers at 1 extreme are good (indicated in green), and another are bad (indicated in red) relative to the rest. the reverse will help you whenever small numbers are good. do not use it wherever this relative value judgement makes no sense, as in population counts (more aren't better or worse, just different)

**Comment by kyleahall** [comment]
@zang0 Where do we put these properties? Backend or frontend? I'm not seeing an example in the existing config.

**Comment by aliciatb** [comment]
Resolved in odn-backend commit, https://github.com/socrata/odn-backend/commit/4df6673090c520052c62c3dadd49189eeffcda63

**Comment by zang0** [comment]
closing this, filing specific fails. conf is in odn-backend/data/sources.json
