### ISSUE TITLE
crime bar chart names clipped

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#556]
https://opendatanetwork-staging.herokuapp.com/entity/1600000US2622000/Detroit_MI/crime.fbi_ucr.rate?crime_type=Aggravated%20assault&year=2014

![screen shot 2016-09-09 at 9 40 27 am](https://cloud.githubusercontent.com/assets/1051776/18395024/78be1bec-7671-11e6-8cca-7cb05e52149c.png)

**Comment by ToshMeston** [comment]
Switched to bar charts so there is more room to display the long incident names.  Fixed.

**Comment by zang0** [comment]
looks great!
