### ISSUE TITLE
awkward NLG statements

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#557]
Drop case on drop down texts, if constraint = year, say "in"

_1 https://opendatanetwork-staging.herokuapp.com/entity/1600000US2622000/Detroit_MI/crime.fbi_ucr.count?crime_type=Aggravated%20assault&year=2014

The Crime incident count of Detroit, MI was 9,191 for the crime_type of Aggravated assault and the year of 2014.

should be

The crime incident count of Detroit, MI was 9,191 for aggravated assault in 2014.

_2 https://opendatanetwork-staging.herokuapp.com/entity/1600000US2622000/Detroit_MI/jobs.earnings.median_earnings?year=2013

The Median Earnings of Detroit, MI was $20,283 for the year of 2013.

should read

The median earnings of Detroit, MI was $20,283 in 2013.

**Comment by aaasen** [comment]
Fixed by https://github.com/socrata/odn-backend/issues/57
