### ISSUE TITLE
dup questions in autosuggest for crime

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#558]
![screen shot 2016-09-09 at 10 50 57 am](https://cloud.githubusercontent.com/assets/1051776/18397092/72d12940-767b-11e6-8fb4-4eddb2a6c603.png)

**Comment by aaasen** [comment]
One is coming from `city_crime` and another from `fbi_ucr`. I redirected `city_crime` to `fbi_ucr` so that the links won't 404, but we should remove all `city_crime` questions from autosuggest. @chrismetcalf

**Comment by zang0** [comment]
to @chrismetcalf to update the dataset.

**Comment by chrismetcalf** [comment]
@aaasen Do the autosuggest changes in `staging` update the questions autosuggest too, or do I still need to regen off my old branch?

**Comment by aaasen** [comment]
My autosuggest changes in backend staging will make the questions autosuggest dataset obsolete so I think we can close this one and not regenerate the dataset

**Comment by chrismetcalf** [comment]
Cool, thanks @aaasen
