### ISSUE TITLE
category query results are odd

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#560]
lets verify the cetera queries are identical.

see:

_1 https://opendatanetwork-staging.herokuapp.com/search?categories=finance&ref=hp

vs

http://www.opendatanetwork.com/search?categories=finance

_2 https://opendatanetwork-staging.herokuapp.com/search?categories=public%20safety&ref=hp

vs

http://www.opendatanetwork.com/search?categories=public%20safety

**Comment by aaasen** [comment]
You can now see the full Cetera query in the API popup. The only difference between the queries is that staging uses `only=datasets`. Not sure why this would make the results so different.

**Comment by aaasen** [comment]
Queries are now the same as production. Any discrepancies now are due to the production cache being stale.
