### ISSUE TITLE
join the open data network on hp fails to render form

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#563]
https://opendatanetwork-staging.herokuapp.com/join-open-data-network

**Comment by aaasen** [comment]
Looks like there is a cert issue when we try to get https://discover.socrata.com/js/forms2/js/forms2.min.js 

I can't even get to https://discover.socrata.com/ right now, Chrome says that the connection is not private. This looks like a much bugger issue than a search form not rendering...

**Comment by zang0** [comment]
ok, can we just yank the form entirely from the page entirely for now, and punt to v.9. @chrismetcalf can you chase this down w/ the devops guys and track progress?

**Comment by aaasen** [comment]
This will also affect production if the site is loaded over HTTPS. I think we should just leave it in since the problem should resolve itself shortly.

**Comment by zang0** [comment]
ok. punting then so we remember to check. still want to poke devops.

**Comment by zang0** [comment]
to chris to poke devops

**Comment by chrismetcalf** [comment]
Fixed in https://github.com/socrata/opendatanetwork.com/pull/601

**Comment by chrismetcalf** [comment]
Merged to staging
