### ISSUE TITLE
drop down not matching table perms

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#565]
looks like this one's back:

https://opendatanetwork-staging.herokuapp.com/entity/8600000US98019-8600000US98117/98019_ZIP_Code-98117_ZIP_Code/education.graduation_rates.percent_less_than_9th_grade?year=2013

note: all the drop down vals aren't present in the table, only 2 there

**Comment by aaasen** [comment]
Fixed this. Now, if a variable is not specified on a chart config, all variables in the dataset will be used.
