### ISSUE TITLE
don't show side badges in mobile view

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#566]
https://opendatanetwork-staging.herokuapp.com/search?q=results&categories=environment
open in mobile view, note green badge causes awkward wrap

![screen shot 2016-09-09 at 12 13 32 pm](https://cloud.githubusercontent.com/assets/1051776/18399662/ec1ecaf4-7686-11e6-8a74-242008ef5c85.png)

**Comment by ToshMeston** [comment]
Fixed.
