### ISSUE TITLE
default landing in mobile from search should have refine results open

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#568]
only when coming from region search (not question clicks (in search or as), should have refine results tab expanded. recall this is because in the region (e.g. seattle) search / autosuggest case, the user had no topical context and should know why we're suddenly showing population data. when they come from a question, the originating context is obvious (i.e. they asked the ?)

repro:
go here
https://opendatanetwork-staging.herokuapp.com
in mobile view. search or autosuggest to seattle, note: refine results is closed in this case. compare to prod. note: ONLY in this case, i.e. not from a question click, and ONLY in mobile, the refine results is open in prod.

**Comment by aaasen** [comment]
Now, the refine will be open on mobile when coming from searching or suggesting a region. I implemented this by adding a `ref` parameter of `search-entity` or `suggest-entity` to the URLs. Also added this to other URLs, for example, the "compare this data" box sets `ref=compare-entity` and "compare this data" links set `ref=related-peer`. In the future we can use these referrers for analytics.
