### ISSUE TITLE
questions wrap pushes main column around instead of wrapping text 

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#570]
https://opendatanetwork-staging.herokuapp.com/entity/1600000US5356695/Puyallup_WA/education.graduation_rates.percent_less_than_9th_grade?year=2013

note: left column right end point doesn't always align w./ the black open data network rectangle in the upper left. looks like questions length pushes it around when you click through the tier 1 menus.

![screen shot 2016-09-09 at 3 14 58 pm](https://cloud.githubusercontent.com/assets/1051776/18404610/76cefca0-76a0-11e6-922c-fc9ea01d8c74.png)
![screen shot 2016-09-09 at 3 14 50 pm](https://cloud.githubusercontent.com/assets/1051776/18404611/76d33e82-76a0-11e6-8958-679f888c2bd4.png)

**Comment by ToshMeston** [comment]
Fixed.
