### ISSUE TITLE
cap questions in search results @ 2 rows

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#571]
see:

https://opendatanetwork-staging.herokuapp.com/search?q=rapid+city

we want:

_1 questions should have a "Show More" 
_2 need to not show more than 2 rows for the Regions for "rapid city" (currently shows 3)
_3 it is ok if the region show more does not also have a "Show More" (ok if it does)

**Comment by aaasen** [comment]
So just get rid of "Show More"?

**Comment by zang0** [comment]
sorry looks like I miss typed the title. what we want:

_1 questions should have a "Show More" 
_2 need to not show more than 2 rows for the Regions for "rapid city" (currently shows 3)
_3 it is ok if the region show more does not also have a "Show More" (ok if it does)

**Comment by aaasen** [comment]
OK that makes more sense. I was a bit confused. I'll fix this tomorrow.
