### ISSUE TITLE
missing place/metro etc labels in search results

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#572]
https://opendatanetwork-staging.herokuapp.com/search?q=rapid+city

compare to prod - note: the labels don't consistently show

**Comment by aaasen** [comment]
Looks like someone added townships to the [ODN Entities dataset](https://odn.data.socrata.com/dataset/ODN-Entities/6gkm-yf7x) for Michigan, but they aren't referenced by any of the Michigan datasets so we don't have any data to render a page with. Just showing a [404 page](https://opendatanetwork-staging.herokuapp.com/entity/0610000US2608134000/Grand_Rapids_City_MI) now. 

@aliciatb @kyleahall Do we need to have these townships? Are they used anywhere? If not, they should be removed from the list of entities.

**Comment by aaasen** [comment]
Rest covered by #574
