### ISSUE TITLE
Missing geodata for some large entities

### ISSUE THREAD

**Issue by aaasen** [socrata/opendatanetwork.com#573]
We seem to be missing geodata for some entites. For example, maps don't render on [NYC](https://opendatanetwork-staging.herokuapp.com/entity/1600000US3651000/New_York_NY/demographics.population.count?year=2013) or [San Francisco](https://opendatanetwork-staging.herokuapp.com/entity/1600000US0667000/San_Francisco_CA/demographics.population.count?year=2013). I'm pretty confused by this since the data is visible on the map in our [geographical dataset](https://odn.data.socrata.com/dataset/ODN-Geodata-Places-V2/funa-vn5h), but querying for [data about NYC gives no results](https://odn.data.socrata.com/resource/rmqq-dzu4.json?id=1600000US3651000). I've already made sure that the IDs are the same.

@chrismetcalf any ideas? The fact that I can see the data in the Socrata map but not access it through a query makes me think that it's a Socrata issue and not an ODN one.

**Comment by chrismetcalf** [comment]
@aaasen Which endpoint are you using and how did you import this dataset? It looks like it has two layers, and only one of them has `New York, NY` in it. I found it with this query:

    GET https://odn.data.socrata.com/resource/gttw-hkqm.json?$select=name&$limit=5&$where=name%20LIKE%20%27New%20York%25%27

The two endpoints, one for each layer:
- https://dev.socrata.com/foundry/odn.data.socrata.com/gttw-hkqm
- https://dev.socrata.com/foundry/odn.data.socrata.com/rmqq-dzu4

**Comment by aaasen** [comment]
I'm using this endpoint: https://dev.socrata.com/foundry/odn.data.socrata.com/rmqq-dzu4

I imported the data through the Socrata web uploader.

**Comment by aaasen** [comment]
I still have the source file if we need to re-upload it.

**Comment by chrismetcalf** [comment]
Can you put the source file somewhere so I can take a look?

-- 
Chris Metcalf

**Comment by aaasen** [comment]
Here it is: https://drive.google.com/a/socrata.com/file/d/0B9pR2kVj0HXMSkNpYTBIblpvSFk/view?usp=sharing

Beware that it is 50mb of GeoJSON so it is a bit difficult to examine by hand.

**Comment by aliciatb** [comment]
Ann Arbor, MI and Lansing, MI are also missing.

**Comment by zang0** [comment]
@chrismetcalf Can you swing by today so we can resolve? Lane and I are here.

**Comment by zang0** [comment]
Plan:

_1 @chrismetcalf to ask on slack

_2 review local file, upload again, see if there's something about the file that's causing the multi layers to be added

**Comment by chrismetcalf** [comment]
@aaasen Not sure if you saw the response on Slack, but the issue is that there is a mix of Polygons and MultiPolygons in the GeoJSON file. Our platform doesn't allow mixed datatypes within a given layer, so it breaks it into multiple layers.

If you convert the source GeoJSON to make all of the Polygons into single-ring MultiPolygons, so everything is consistent, it should import as a single layer

**Comment by aaasen** [comment]
Changing `MultiPolygon` to `Polygon` worked. The fix is live. Closing.

**Comment by aaasen** [comment]
New dataset is here: https://dev.socrata.com/foundry/odn.data.socrata.com/4w8p-9itj
