### ISSUE TITLE
ODN Api cant tell when there are no more results

### ISSUE THREAD

**Issue by skaros** [socrata/opendatanetwork.com#575]
Hi, I am working on an application (in Java) that would search the ODN API and get me the datasets i want. The problem is that the api is not ever returning an empty JSON, unlike the Socrata datasets, where an empty object is returned when the end offset is reached. no matter what offset number i use, i always get the last page. for example
[http://api.opendatanetwork.com/suggest/v1/dataset?query=checkbook&limit=20&offset=1&app_token=cQovpGcdUT1CSzgYk0KPYdAI0](http://api.opendatanetwork.com/suggest/v1/dataset?query=checkbook&limit=20&offset=1&app_token=cQovpGcdUT1CSzgYk0KPYdAI0)
[http://api.opendatanetwork.com/suggest/v1/dataset?query=checkbook&limit=20&offset=6000000&app_token=cQovpGcdUT1CSzgYk0KPYdAI0](http://api.opendatanetwork.com/suggest/v1/dataset?query=checkbook&limit=20&offset=6000000&app_token=cQovpGcdUT1CSzgYk0KPYdAI0)
have exactly the same results.
I am using the code found on the [Apiary](http://docs.odn.apiary.io/#reference/0/suggestions/get-suggestions) doc of ODN API, like so
	

> Client client = ClientBuilder.newClient();
> 			 response = client.target("http://api.opendatanetwork.com/suggest/v1/" +
> 					"dataset?query=checkbook&limit="+limit+"&offset="+offset)
> 			  .request(MediaType.TEXT_PLAIN_TYPE)
> 			  
> 			  .header("X-App-Token", "cQovpGcdUT1CSzgYk0KPYdAI0")
> 			  .get();

Any work around that?
**Edit**
ok, it seems that it is not paging at all. for example
[http://api.opendatanetwork.com/suggest/v1/dataset?query=checkbook&limit=1&offset=1&app_token=cQovpGcdUT1CSzgYk0KPYdAI0](http://api.opendatanetwork.com/suggest/v1/dataset?query=checkbook&limit=1&offset=0&app_token=cQovpGcdUT1CSzgYk0KPYdAI0)
and
[http://api.opendatanetwork.com/suggest/v1/dataset?query=checkbook&limit=1&offset=3&app_token=cQovpGcdUT1CSzgYk0KPYdAI0](http://api.opendatanetwork.com/suggest/v1/dataset?query=checkbook&limit=1&offset=3&app_token=cQovpGcdUT1CSzgYk0KPYdAI0)
has the exact same result! the documentation on the Apiary page is not so helpful!

**Comment by aaasen** [comment]
@skaros, the `/suggest` endpoint is used for autosuggestion of datasets, for example in the search box of opendatanetwork.com. It does not accept an `offset` parameter. If you want to search through the entire catalog of Socrata datasets, try using the [Socrata Discovery API](http://docs.socratadiscovery.apiary.io/). 

For example, to find twenty datasets for the term "checkbook":
https://api.us.socrata.com/api/catalog/v1?q=checkbook&limit=20

Sorry for the confusion, and let me know if you have any more questions.

**Comment by skaros** [comment]
@aaasen Thanks for that. I knew that url, but i was using it with a `BufferedReader`, causing it to hang some times, so I tried to use the API and the code provided at the doc. Now i used the address you suggest with the code from the API and it seems to work. Thanks
