### ISSUE TITLE
compares on MI finance for non MI cities blow up

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#579]
https://opendatanetwork-staging.herokuapp.com/entity/1600000US2622000/Detroit_MI/finance.michigan_debt.debt_service?year=2013

click on COMPARE THIS DATA 

Cleveland

note: 404/variable not found: finance

can we not show the compare this for the MI/finance stuff or a friendlier message for now.

**Comment by aaasen** [comment]
For now, "Compare this data" will not show up on the Michigan Finance category. In the future, we could add a variable parameter to `/related` that would filter results to include only regions with data.
