### ISSUE TITLE
Favicon (and logo) are old Socrata Branding/Colors

### ISSUE THREAD

**Issue by sniderna** [socrata/opendatanetwork.com#591]
The favicon for the ODN is the Red and Black Socrata logo, rather than the blue/orange updated branding, and the Open data Network logo is reminiscent of the Black/Red logo.

Not sure if this is a conscious decision that the ODN is going to be the "Red and Black" branded Socrata site

**Comment by chrismetcalf** [comment]
> I’ve updated the logo with our official color palette. Attached are some assets to update the site. I’ve included two options and the css to updated the logo.
> 
> Colors used in option 1:
> 
> Header Background: #8e98a1
> Search Button: #288dc1
> 
> Colors used in option 2:
> 
> Header Background: #288dc1
> Search Button: #e28432

[ODN-assets.zip](https://github.com/socrata/opendatanetwork.com/files/542819/ODN-assets.zip)
