### ISSUE TITLE
health insurance data issues

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#603]
1. we should stop light the maps - higher uninsured rates are worse than lower.

2. i would change the Percent Insured drop down to be more explicit as this is used in title and question generation. Specifically:

drop down 1:

change: Insurance to: Health Insurance

Percent Uninsured > Percent Without Health Insurance

3. top search bar > search for washington, note, click on the Health tab does not show Insurance as an option despite data being available for WA. OR and North Carolina are ok.

4. "Total Individuals" doesn't read right or make sense.

The total individuals of Idaho was 950,344 for 18 to 64, all races, both sexes and all income levels in 2014.

What are these? Total individuals on attempting to get insurance?

5. some latin in the source citation, see: http://bit.ly/2drbFFR

**Comment by chrismetcalf** [comment]
Trying to get this out along with #604. I've got item 1 from the above fixed, and I've also tightened up the variable human names, but for item 2 I'm going to have to do a full replace on the variables dataset to remove the old variable names.

Going to do that swap out this evening.

**Comment by chrismetcalf** [comment]
> we should stop light the maps - higher uninsured rates are worse than lower.

Done!

> i would change the Percent Insured drop down to be more explicit as this is used in title and question generation. Specifically:
> 
> drop down 1:
> 
> change: Insurance to: Health Insurance

Done.

> Percent Uninsured > Percent Without Health Insurance

Done.
 
> top search bar > search for washington, note, click on the Health tab does not show Insurance as an option despite data being available for WA. OR and North Carolina are ok.

Not quite sure how you're finding that, I wonder if you got an old cached page. It worked fine for me.

> "Total Individuals" doesn't read right or make sense.
> The total individuals of Idaho was 950,344 for 18 to 64, all races, both sexes and all income levels in 2014.
> 
> What are these? Total individuals on attempting to get insurance?

That's the number of residents matching the demographic filters applied.
