### ISSUE TITLE
stoplights off on percent without insurance

### ISSUE THREAD

**Issue by zang0** [socrata/opendatanetwork.com#609]
https://www.opendatanetwork.com/entity/0400000US12/Florida/health.health_insurance.pctui?year=2014&age=18%20to%2064&race=All%20races&sex=Both%20sexes&income=All%20income%20levels

note: red should be bad, green should be good. higher insuranceless rates are bad. use stop light reverse=true.

**Comment by chrismetcalf** [comment]
Fixed this yesterday
